/*******************************************************************************
 * File Name: project.h
 * cydsfit No Version Information Found
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <PWM_1.h>
#include <Clock_1.h>
#include <UP.h>
#include <UP_aliases.h>
#include <DOWN.h>
#include <DOWN_aliases.h>
#include <PWM_2.h>
#include <Clock_2.h>
#include <FRONT.h>
#include <FRONT_aliases.h>
#include <BACK.h>
#include <BACK_aliases.h>
#include <Ana.h>
#include <Ana_aliases.h>
#include <isr_1.h>
#include <Clock_4.h>
#include <UART_1.h>
#include <Rx_1.h>
#include <Rx_1_aliases.h>
#include <ADC_DelSig_1.h>
#include <UART_1_IntClock.h>
#include <ADC_DelSig_1_AMux.h>
#include <ADC_DelSig_1_Ext_CP_Clk.h>
#include <ADC_DelSig_1_IRQ.h>
#include <ADC_DelSig_1_theACLK.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>
#include <PSoC3_8051.h>

/*[]*/

