/***********************************************************************/
/*                                                                     */
/*  FILE        :serial01.c                                            */
/*  DATE        :Sun, May 18, 2008                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :SH7125                                                */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.5).     */
/*                                                                     */
/***********************************************************************/
                  
#include "iodefine.h"
#include "sci_mod.h"

void main(void){
        unsigned char c;
        short ret;

        SCI_init();           // SCI‰Šú‰»

        SCI_printf("\n");
        SCI_printf("--------------------------------------------\n");
        SCI_printf(" Serial Communication Test Program \n");
        SCI_printf("--------------------------------------------\n");

        SCI_printf("\n Push Any Key\n");
        SCI_putc('>');

        while(1){
                if(s_getc(&c)){
                        SCI_putc(c);
                        if(c=='\n') SCI_putc('>');
                }
        }
}
