/***********************************************************************/
/*                                                                     */
/*  FILE        :stacksct.h                                            */
/*  DATE        :Sun, May 18, 2008                                     */
/*  DESCRIPTION :Setting of Stack area                                 */
/*  CPU TYPE    :SH7125                                                */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.5).     */
/*                                                                     */
/***********************************************************************/
#pragma stacksize 0x400         /* Do not modify this line. */
