/*******************************************************************************
 * File Name: project.h  
 * PSoC Creator 2.2 Component Pack 6
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <LED_1.h>
#include <LED_1_aliases.h>
#include <Counter_1.h>
#include <Clock_1.h>
#include <LCD_Char_1.h>
#include <I2C_1.h>
#include <I2C_1_PVT.h>
#include <SCL_1.h>
#include <SCL_1_aliases.h>
#include <SDA_1.h>
#include <SDA_1_aliases.h>
#include <LCD_Char_1_LCDPort.h>
#include <LCD_Char_1_LCDPort_aliases.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>
#include <PSoC3_8051.h>

/*[]*/

