/*******************************************************************************
 * File Name: project.h
 * PSoC Creator 3.0
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <PWM_1.h>
#include <PWM_2.h>
#include <Clock_1.h>
#include <Clock_2.h>
#include <Pin_1.h>
#include <Pin_1_aliases.h>
#include <Pin_2.h>
#include <Pin_2_aliases.h>
#include <Pin_3.h>
#include <Pin_3_aliases.h>
#include <Pin_4.h>
#include <Pin_4_aliases.h>
#include <Pin_5.h>
#include <Pin_5_aliases.h>
#include <Pin_6.h>
#include <Pin_6_aliases.h>
#include <Pin_7.h>
#include <Pin_7_aliases.h>
#include <Pin_8.h>
#include <Pin_8_aliases.h>
#include <LIN_1.h>
#include <UART_1.h>
#include <LIN_1_UART.h>
#include <LIN_1_IntClk.h>
#include <UART_1_IntClock.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>
#include <PSoC3_8051.h>

/*[]*/

