/*******************************************************************************
 * File Name: project.h
 * PSoC Creator 3.0 Component Pack 7
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <PWM_1.h>
#include <PWM_2.h>
#include <Clock_1.h>
#include <Motor_1_A.h>
#include <Motor_1_A_aliases.h>
#include <Motor_1_B.h>
#include <Motor_1_B_aliases.h>
#include <Motor_2_A.h>
#include <Motor_2_A_aliases.h>
#include <Motor_2_B.h>
#include <Motor_2_B_aliases.h>
#include <limit_center.h>
#include <limit_center_aliases.h>
#include <rori_R_A.h>
#include <rori_R_A_aliases.h>
#include <limit_left.h>
#include <limit_left_aliases.h>
#include <limit_right.h>
#include <limit_right_aliases.h>
#include <LIN_1.h>
#include <UART_1.h>
#include <QuadDec_R.h>
#include <rori_L_A.h>
#include <rori_L_A_aliases.h>
#include <rori_L_B.h>
#include <rori_L_B_aliases.h>
#include <rori_L_i.h>
#include <rori_L_i_aliases.h>
#include <Clock_3.h>
#include <Clock_4.h>
#include <isr_1.h>
#include <rori_R_B.h>
#include <rori_R_B_aliases.h>
#include <rori_R_i.h>
#include <rori_R_i_aliases.h>
#include <QuadDec_L.h>
#include <LIN_1_UART.h>
#include <LIN_1_IntClk.h>
#include <UART_1_IntClock.h>
#include <QuadDec_R_Cnt16.h>
#include <QuadDec_L_Cnt16.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>
#include <PSoC3_8051.h>

/*[]*/

