/***********************************************************************/
/*                                                                     */
/*  FILE        :LED.c                                                 */
/*  DATE        :Fri, Nov 09, 2012                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :SH7125                                                */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.18).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/***********************************************************************/
                  
#include "iodefine.h"


#define MD0AL PE.DRL.BIT.B0
#define MD1AL PE.DRL.BIT.B1
#define MD0BL PE.DRL.BIT.B2
#define MD1BL PE.DRL.BIT.B3
#define MD0BH PE.DRL.BIT.B4
#define MD1BH PE.DRL.BIT.B5
#define MD0AH PE.DRL.BIT.B6
#define MD1AH PE.DRL.BIT.B7
#define RE0A PB.PR.BIT.B3
#define RE0B PB.DR.BIT.B2
#define RE1A PB.DRL.BIT.B5
#define RE1B PA.DRL.BIT.B5

void main(void)
{
	int i=100;
	PFC.PECRL2.BIT.PE4MD=0;		//IOポートに設定
	PFC.PEIORL.BIT.B0=1;		//出力ポートに設定

	PFC.PEIORL.WORD=0x00FF;		//ちょっと
	
	MD0BH=1;
	MD1BH=1;
	
	while(1){
		while(i--);
		i=2000000;
		PE.DRL.BIT.B0^=1;
		MD1AL^=1;
		
	}

}
