/*******************************************************************************
 * File Name: project.h
 * PSoC Creator 3.0 Component Pack 7
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <PWM_1.h>
#include <PWM_2.h>
#include <Clock_1.h>
#include <Clock_2.h>
#include <Motor_1_r.h>
#include <Motor_1_r_aliases.h>
#include <Motor_1_l.h>
#include <Motor_1_l_aliases.h>
#include <Motor_2_r.h>
#include <Motor_2_r_aliases.h>
#include <Motor_2_l.h>
#include <Motor_2_l_aliases.h>
#include <Position_1.h>
#include <Position_1_aliases.h>
#include <LIN_1.h>
#include <UART_1.h>
#include <ADC_DelSig_1.h>
#include <Clock_4.h>
#include <isr_1.h>
#include <LIN_1_UART.h>
#include <LIN_1_IntClk.h>
#include <UART_1_IntClock.h>
#include <ADC_DelSig_1_AMux.h>
#include <ADC_DelSig_1_Ext_CP_Clk.h>
#include <ADC_DelSig_1_IRQ.h>
#include <ADC_DelSig_1_theACLK.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>
#include <PSoC3_8051.h>

/*[]*/

