/******************************************************************************
*  Generated by PSoC Designer 5.4.2946
******************************************************************************/
#include <m8c.h>
// x_a_low address and mask defines
#pragma	ioport	x_a_low_Data_ADDR:	0x0
BYTE			x_a_low_Data_ADDR;
#pragma	ioport	x_a_low_DriveMode_0_ADDR:	0x100
BYTE			x_a_low_DriveMode_0_ADDR;
#pragma	ioport	x_a_low_DriveMode_1_ADDR:	0x101
BYTE			x_a_low_DriveMode_1_ADDR;
#pragma	ioport	x_a_low_DriveMode_2_ADDR:	0x3
BYTE			x_a_low_DriveMode_2_ADDR;
#pragma	ioport	x_a_low_GlobalSelect_ADDR:	0x2
BYTE			x_a_low_GlobalSelect_ADDR;
#pragma	ioport	x_a_low_IntCtrl_0_ADDR:	0x102
BYTE			x_a_low_IntCtrl_0_ADDR;
#pragma	ioport	x_a_low_IntCtrl_1_ADDR:	0x103
BYTE			x_a_low_IntCtrl_1_ADDR;
#pragma	ioport	x_a_low_IntEn_ADDR:	0x1
BYTE			x_a_low_IntEn_ADDR;
#define x_a_low_MASK 0x1
// x_b_low address and mask defines
#pragma	ioport	x_b_low_Data_ADDR:	0x0
BYTE			x_b_low_Data_ADDR;
#pragma	ioport	x_b_low_DriveMode_0_ADDR:	0x100
BYTE			x_b_low_DriveMode_0_ADDR;
#pragma	ioport	x_b_low_DriveMode_1_ADDR:	0x101
BYTE			x_b_low_DriveMode_1_ADDR;
#pragma	ioport	x_b_low_DriveMode_2_ADDR:	0x3
BYTE			x_b_low_DriveMode_2_ADDR;
#pragma	ioport	x_b_low_GlobalSelect_ADDR:	0x2
BYTE			x_b_low_GlobalSelect_ADDR;
#pragma	ioport	x_b_low_IntCtrl_0_ADDR:	0x102
BYTE			x_b_low_IntCtrl_0_ADDR;
#pragma	ioport	x_b_low_IntCtrl_1_ADDR:	0x103
BYTE			x_b_low_IntCtrl_1_ADDR;
#pragma	ioport	x_b_low_IntEn_ADDR:	0x1
BYTE			x_b_low_IntEn_ADDR;
#define x_b_low_MASK 0x2
// y_a_low address and mask defines
#pragma	ioport	y_a_low_Data_ADDR:	0x0
BYTE			y_a_low_Data_ADDR;
#pragma	ioport	y_a_low_DriveMode_0_ADDR:	0x100
BYTE			y_a_low_DriveMode_0_ADDR;
#pragma	ioport	y_a_low_DriveMode_1_ADDR:	0x101
BYTE			y_a_low_DriveMode_1_ADDR;
#pragma	ioport	y_a_low_DriveMode_2_ADDR:	0x3
BYTE			y_a_low_DriveMode_2_ADDR;
#pragma	ioport	y_a_low_GlobalSelect_ADDR:	0x2
BYTE			y_a_low_GlobalSelect_ADDR;
#pragma	ioport	y_a_low_IntCtrl_0_ADDR:	0x102
BYTE			y_a_low_IntCtrl_0_ADDR;
#pragma	ioport	y_a_low_IntCtrl_1_ADDR:	0x103
BYTE			y_a_low_IntCtrl_1_ADDR;
#pragma	ioport	y_a_low_IntEn_ADDR:	0x1
BYTE			y_a_low_IntEn_ADDR;
#define y_a_low_MASK 0x4
// y_b_low address and mask defines
#pragma	ioport	y_b_low_Data_ADDR:	0x0
BYTE			y_b_low_Data_ADDR;
#pragma	ioport	y_b_low_DriveMode_0_ADDR:	0x100
BYTE			y_b_low_DriveMode_0_ADDR;
#pragma	ioport	y_b_low_DriveMode_1_ADDR:	0x101
BYTE			y_b_low_DriveMode_1_ADDR;
#pragma	ioport	y_b_low_DriveMode_2_ADDR:	0x3
BYTE			y_b_low_DriveMode_2_ADDR;
#pragma	ioport	y_b_low_GlobalSelect_ADDR:	0x2
BYTE			y_b_low_GlobalSelect_ADDR;
#pragma	ioport	y_b_low_IntCtrl_0_ADDR:	0x102
BYTE			y_b_low_IntCtrl_0_ADDR;
#pragma	ioport	y_b_low_IntCtrl_1_ADDR:	0x103
BYTE			y_b_low_IntCtrl_1_ADDR;
#pragma	ioport	y_b_low_IntEn_ADDR:	0x1
BYTE			y_b_low_IntEn_ADDR;
#define y_b_low_MASK 0x8
// z_a_low address and mask defines
#pragma	ioport	z_a_low_Data_ADDR:	0x0
BYTE			z_a_low_Data_ADDR;
#pragma	ioport	z_a_low_DriveMode_0_ADDR:	0x100
BYTE			z_a_low_DriveMode_0_ADDR;
#pragma	ioport	z_a_low_DriveMode_1_ADDR:	0x101
BYTE			z_a_low_DriveMode_1_ADDR;
#pragma	ioport	z_a_low_DriveMode_2_ADDR:	0x3
BYTE			z_a_low_DriveMode_2_ADDR;
#pragma	ioport	z_a_low_GlobalSelect_ADDR:	0x2
BYTE			z_a_low_GlobalSelect_ADDR;
#pragma	ioport	z_a_low_IntCtrl_0_ADDR:	0x102
BYTE			z_a_low_IntCtrl_0_ADDR;
#pragma	ioport	z_a_low_IntCtrl_1_ADDR:	0x103
BYTE			z_a_low_IntCtrl_1_ADDR;
#pragma	ioport	z_a_low_IntEn_ADDR:	0x1
BYTE			z_a_low_IntEn_ADDR;
#define z_a_low_MASK 0x10
// z_b_low address and mask defines
#pragma	ioport	z_b_low_Data_ADDR:	0x0
BYTE			z_b_low_Data_ADDR;
#pragma	ioport	z_b_low_DriveMode_0_ADDR:	0x100
BYTE			z_b_low_DriveMode_0_ADDR;
#pragma	ioport	z_b_low_DriveMode_1_ADDR:	0x101
BYTE			z_b_low_DriveMode_1_ADDR;
#pragma	ioport	z_b_low_DriveMode_2_ADDR:	0x3
BYTE			z_b_low_DriveMode_2_ADDR;
#pragma	ioport	z_b_low_GlobalSelect_ADDR:	0x2
BYTE			z_b_low_GlobalSelect_ADDR;
#pragma	ioport	z_b_low_IntCtrl_0_ADDR:	0x102
BYTE			z_b_low_IntCtrl_0_ADDR;
#pragma	ioport	z_b_low_IntCtrl_1_ADDR:	0x103
BYTE			z_b_low_IntCtrl_1_ADDR;
#pragma	ioport	z_b_low_IntEn_ADDR:	0x1
BYTE			z_b_low_IntEn_ADDR;
#define z_b_low_MASK 0x20
// EzI2Cs_1SDA address and mask defines
#pragma	ioport	EzI2Cs_1SDA_Data_ADDR:	0x4
BYTE			EzI2Cs_1SDA_Data_ADDR;
#pragma	ioport	EzI2Cs_1SDA_DriveMode_0_ADDR:	0x104
BYTE			EzI2Cs_1SDA_DriveMode_0_ADDR;
#pragma	ioport	EzI2Cs_1SDA_DriveMode_1_ADDR:	0x105
BYTE			EzI2Cs_1SDA_DriveMode_1_ADDR;
#pragma	ioport	EzI2Cs_1SDA_DriveMode_2_ADDR:	0x7
BYTE			EzI2Cs_1SDA_DriveMode_2_ADDR;
#pragma	ioport	EzI2Cs_1SDA_GlobalSelect_ADDR:	0x6
BYTE			EzI2Cs_1SDA_GlobalSelect_ADDR;
#pragma	ioport	EzI2Cs_1SDA_IntCtrl_0_ADDR:	0x106
BYTE			EzI2Cs_1SDA_IntCtrl_0_ADDR;
#pragma	ioport	EzI2Cs_1SDA_IntCtrl_1_ADDR:	0x107
BYTE			EzI2Cs_1SDA_IntCtrl_1_ADDR;
#pragma	ioport	EzI2Cs_1SDA_IntEn_ADDR:	0x5
BYTE			EzI2Cs_1SDA_IntEn_ADDR;
#define EzI2Cs_1SDA_MASK 0x20
// EzI2Cs_1SCL address and mask defines
#pragma	ioport	EzI2Cs_1SCL_Data_ADDR:	0x4
BYTE			EzI2Cs_1SCL_Data_ADDR;
#pragma	ioport	EzI2Cs_1SCL_DriveMode_0_ADDR:	0x104
BYTE			EzI2Cs_1SCL_DriveMode_0_ADDR;
#pragma	ioport	EzI2Cs_1SCL_DriveMode_1_ADDR:	0x105
BYTE			EzI2Cs_1SCL_DriveMode_1_ADDR;
#pragma	ioport	EzI2Cs_1SCL_DriveMode_2_ADDR:	0x7
BYTE			EzI2Cs_1SCL_DriveMode_2_ADDR;
#pragma	ioport	EzI2Cs_1SCL_GlobalSelect_ADDR:	0x6
BYTE			EzI2Cs_1SCL_GlobalSelect_ADDR;
#pragma	ioport	EzI2Cs_1SCL_IntCtrl_0_ADDR:	0x106
BYTE			EzI2Cs_1SCL_IntCtrl_0_ADDR;
#pragma	ioport	EzI2Cs_1SCL_IntCtrl_1_ADDR:	0x107
BYTE			EzI2Cs_1SCL_IntCtrl_1_ADDR;
#pragma	ioport	EzI2Cs_1SCL_IntEn_ADDR:	0x5
BYTE			EzI2Cs_1SCL_IntEn_ADDR;
#define EzI2Cs_1SCL_MASK 0x80
// AGND address and mask defines
#pragma	ioport	AGND_Data_ADDR:	0x8
BYTE			AGND_Data_ADDR;
#pragma	ioport	AGND_DriveMode_0_ADDR:	0x108
BYTE			AGND_DriveMode_0_ADDR;
#pragma	ioport	AGND_DriveMode_1_ADDR:	0x109
BYTE			AGND_DriveMode_1_ADDR;
#pragma	ioport	AGND_DriveMode_2_ADDR:	0xb
BYTE			AGND_DriveMode_2_ADDR;
#pragma	ioport	AGND_GlobalSelect_ADDR:	0xa
BYTE			AGND_GlobalSelect_ADDR;
#pragma	ioport	AGND_IntCtrl_0_ADDR:	0x10a
BYTE			AGND_IntCtrl_0_ADDR;
#pragma	ioport	AGND_IntCtrl_1_ADDR:	0x10b
BYTE			AGND_IntCtrl_1_ADDR;
#pragma	ioport	AGND_IntEn_ADDR:	0x9
BYTE			AGND_IntEn_ADDR;
#define AGND_MASK 0x10
