//*****************************************************************************
//*****************************************************************************
//  FILENAME: MBM_1.h
//   Version: 1.1, Updated on 2013/5/19 at 10:43:55
//  Generated by PSoC Designer 5.4.2946
//
//  DESCRIPTION: MBM_1 User Module C Language interface file  
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2013. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************

#ifndef MBM_1_include
#define MBM_1_include

#include <m8c.h>

//--------------------------------------------------
// constants for mailboxes
//--------------------------------------------------
#define MBM_1_SERVICE_VARS_ABOVE               0
#define MBM_1_SERVICE_VARS_BELOW               1
// mailbox service variables position
#define MBM_1_SERVICE_VARS_POSITION            MBM_1_SERVICE_VARS_ABOVE // Position of service variables in structure

// offset of service bytes
#define MBM_1_CONFIG_0                         0
#define MBM_1_CONFIG_1                         1

#define MBM_1_BUSY                             0x80   // Busy Flag - set by the slave to tell the host not to read data until cleared
#define MBM_1_DIRTY                            0x40   // Dirty Flag - set by the host to denote that data is in the process of being written and that the slave should not read data from the mailbox until it is cleared

// variables aliases (offset inside of structure)
// access to some structure member:
//(TYPE)* (MBM_1_pMyMailbox+Alias)
#define MAILBOXCONFIG0		 0x00
#define MAILBOXCONFIG1		 0x01
#define OUTBOXFLAG		 0x02
#define TBRAKEFLAG		 0x03
#define X_TRS		 0x04
#define Y_TRS		 0x05
#define Z_TRS		 0x06
#define BSHIFT_X		 0x07
#define KP_X		 0x08
#define KI_X		 0x09
#define BSHIFT_Y		 0x0A
#define KP_Y		 0x0B
#define KI_Y		 0x0C
#define BSHIFT_Z		 0x0D
#define KP_Z		 0x0E
#define KI_Z		 0x0F
#define INBOXFLAG		 0x10
#define CBRAKEFLAG		 0x11
#define X_CRS		 0x12
#define Y_CRS		 0x13
#define Z_CRS		 0x14


//--------------------------------------------------
// typedefs for mailboxes
//--------------------------------------------------

typedef struct
{
	BYTE OutboxFlag; 			// Outbox Flag
	BYTE TBrakeFlag; 			// target brake flag
	BYTE X_trs; 			// X motor target rotation speed
	BYTE Y_trs; 			// Y motor target rotation speed
	BYTE Z_trs; 			// Z motor target rotation speed
	BYTE bshift_X; 			// X bit shift
	BYTE Kp_X; 			// Kp : X motor
	BYTE Ki_X; 			// Ki : X motor
	BYTE bshift_Y; 			// Y bit shift
	BYTE Kp_Y; 			// Kp : Y motor
	BYTE Ki_Y; 			// Ki : Y motor
	BYTE bshift_Z; 			// Z bit shift
	BYTE Kp_Z; 			// Kp : Z motor
	BYTE Ki_Z; 			// Ki : Z motor

} MBM_1_Outbox;

typedef struct
{
	BYTE InboxFlag; 			// Inbox Flag
	BYTE CBrakeFlag; 			// current brake flag
	BYTE X_crs; 			// X motor current rotation speed
	BYTE Y_crs; 			// Y motor current rotation speed
	BYTE Z_crs; 			// Z motor current rotaiton speed

} MBM_1_Inbox;

typedef struct
{
    #if (MBM_1_SERVICE_VARS_POSITION == MBM_1_SERVICE_VARS_ABOVE)

	BYTE MailboxConfig0; 			// Reserved for Mailbox UM usage
	BYTE MailboxConfig1; 			// Reserved for Mailbox UM usage

    #endif

    MBM_1_Outbox Outbox;
    MBM_1_Inbox Inbox;

    #if (MBM_1_SERVICE_VARS_POSITION == MBM_1_SERVICE_VARS_BELOW)

	BYTE MailboxConfig0; 			// Reserved for Mailbox UM usage
	BYTE MailboxConfig1; 			// Reserved for Mailbox UM usage

    #endif
} MBM_1_Mailbox;

//-------------------------------------------------
// C prototypes of the MBM_1 API.
//-------------------------------------------------
extern void MBM_1_InitializeMailbox(void);
extern void MBM_1_SetBusyFlag(void);
extern void MBM_1_ClearBusyFlag(void);
extern BYTE MBM_1_CheckDirtyFlag(void);

// ---------------------------------------------------------------------------
// MBM_1 global mailbox variable in RAM
// ---------------------------------------------------------------------------
extern MBM_1_Mailbox MBM_1_MyMailbox;
extern MBM_1_Mailbox* MBM_1_pMyMailbox;

#endif
