//*****************************************************************************
//*****************************************************************************
//  FILENAME: PRS32_Z.h
//   Version: 3.4, Updated on 2013/5/19 at 10:44:2
//  Generated by PSoC Designer 5.4.2946
//
//  DESCRIPTION: PRS32 User Module C Language interface file.
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2013. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef PRS32_Z_INCLUDE
#define PRS32_Z_INCLUDE

#include <m8c.h>

#pragma fastcall16  PRS32_Z_Start
#pragma fastcall16  PRS32_Z_Stop
#pragma fastcall16  PRS32_Z_WriteSeed
#pragma fastcall16  PRS32_Z_WritePolynomial
#pragma fastcall16  PRS32_Z_ReadPRS

//-------------------------------------------------
// Prototypes of the PRS32_Z API.
//-------------------------------------------------
extern void  PRS32_Z_Start(void);
extern void  PRS32_Z_Stop(void);
extern void  PRS32_Z_WriteSeed(DWORD dwSeed);
extern void  PRS32_Z_WritePolynomial(DWORD dwPolynomial);
extern void  PRS32_Z_ReadPRS(DWORD * pdwPRSNumber);
//-------------------------------------------------
// Constants for PRS32_Z API's.
//-------------------------------------------------

//-------------------------------------------------
// Register Addresses for PRS32_Z
//-------------------------------------------------
#pragma ioport  PRS32_Z_CONTROL_REG_LSB:    0x053          //Control register LSB
BYTE            PRS32_Z_CONTROL_REG_LSB;
#pragma ioport  PRS32_Z_CONTROL_REG_ISB1:   0x057          //Control register ISB1
BYTE            PRS32_Z_CONTROL_REG_ISB1;
#pragma ioport  PRS32_Z_CONTROL_REG_ISB2:   0x05b          //Control register ISB2
BYTE            PRS32_Z_CONTROL_REG_ISB2;
#pragma ioport  PRS32_Z_CONTROL_REG_MSB:    0x05f          //Control register MSB
BYTE            PRS32_Z_CONTROL_REG_MSB;
#pragma ioport  PRS32_Z_SHIFT_REG_LSB:  0x050              //Shift register LSB
BYTE            PRS32_Z_SHIFT_REG_LSB;
#pragma ioport  PRS32_Z_SHIFT_REG_ISB1: 0x054              //Shift register ISB1
BYTE            PRS32_Z_SHIFT_REG_ISB1;
#pragma ioport  PRS32_Z_SHIFT_REG_ISB2: 0x058              //Shift register ISB2
BYTE            PRS32_Z_SHIFT_REG_ISB2;
#pragma ioport  PRS32_Z_SHIFT_REG_MSB:  0x05c              //Shift register MSB
BYTE            PRS32_Z_SHIFT_REG_MSB;
#pragma ioport  PRS32_Z_POLY_REG_LSB:   0x051              //Polynomial register LSB
BYTE            PRS32_Z_POLY_REG_LSB;
#pragma ioport  PRS32_Z_POLY_REG_ISB1:  0x055              //Polynomial register ISB1
BYTE            PRS32_Z_POLY_REG_ISB1;
#pragma ioport  PRS32_Z_POLY_REG_ISB2:  0x059              //Polynomial register ISB2
BYTE            PRS32_Z_POLY_REG_ISB2;
#pragma ioport  PRS32_Z_POLY_REG_MSB:   0x05d              //Polynomial register MSB
BYTE            PRS32_Z_POLY_REG_MSB;
#pragma ioport  PRS32_Z_SEED_REG_LSB:   0x052              //Seed register LSB
BYTE            PRS32_Z_SEED_REG_LSB;
#pragma ioport  PRS32_Z_SEED_REG_ISB1:  0x056              //Seed register ISB1
BYTE            PRS32_Z_SEED_REG_ISB1;
#pragma ioport  PRS32_Z_SEED_REG_ISB2:  0x05a              //Seed register ISB2
BYTE            PRS32_Z_SEED_REG_ISB2;
#pragma ioport  PRS32_Z_SEED_REG_MSB:   0x05e              //Seed register MSB
BYTE            PRS32_Z_SEED_REG_MSB;
#pragma ioport  PRS32_Z_FUNC_REG_LSB:   0x150              //Function register LSB
BYTE            PRS32_Z_FUNC_REG_LSB;
#pragma ioport  PRS32_Z_FUNC_REG_ISB1:  0x154              //Function register ISB1
BYTE            PRS32_Z_FUNC_REG_ISB1;
#pragma ioport  PRS32_Z_FUNC_REG_ISB2:  0x158              //Function register ISB2
BYTE            PRS32_Z_FUNC_REG_ISB2;
#pragma ioport  PRS32_Z_FUNC_REG_MSB:   0x15c              //Function register MSB
BYTE            PRS32_Z_FUNC_REG_MSB;
#pragma ioport  PRS32_Z_INPUT_REG_LSB:  0x151              //Input register LSB
BYTE            PRS32_Z_INPUT_REG_LSB;
#pragma ioport  PRS32_Z_INPUT_REG_ISB1: 0x155              //Input register ISB1
BYTE            PRS32_Z_INPUT_REG_ISB1;
#pragma ioport  PRS32_Z_INPUT_REG_ISB2: 0x159              //Input register ISB2
BYTE            PRS32_Z_INPUT_REG_ISB2;
#pragma ioport  PRS32_Z_INPUT_REG_MSB:  0x15d              //Input register MSB
BYTE            PRS32_Z_INPUT_REG_MSB;
#pragma ioport  PRS32_Z_OUTPUT_REG_LSB: 0x152              //Output register LSB
BYTE            PRS32_Z_OUTPUT_REG_LSB;
#pragma ioport  PRS32_Z_OUTPUT_REG_ISB1:    0x156          //Output register ISB1
BYTE            PRS32_Z_OUTPUT_REG_ISB1;
#pragma ioport  PRS32_Z_OUTPUT_REG_ISB2:    0x15a          //Output register ISB2
BYTE            PRS32_Z_OUTPUT_REG_ISB2;
#pragma ioport  PRS32_Z_OUTPUT_REG_MSB: 0x15e              //Output register MSB
BYTE            PRS32_Z_OUTPUT_REG_MSB;

#endif
// end of file PRS32_Z.h
