//*****************************************************************************
//*****************************************************************************
//  FILENAME: PRS32_X.h
//   Version: 3.4, Updated on 2013/5/19 at 10:44:2
//  Generated by PSoC Designer 5.4.2946
//
//  DESCRIPTION: PRS32 User Module C Language interface file.
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2013. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef PRS32_X_INCLUDE
#define PRS32_X_INCLUDE

#include <m8c.h>

#pragma fastcall16  PRS32_X_Start
#pragma fastcall16  PRS32_X_Stop
#pragma fastcall16  PRS32_X_WriteSeed
#pragma fastcall16  PRS32_X_WritePolynomial
#pragma fastcall16  PRS32_X_ReadPRS

//-------------------------------------------------
// Prototypes of the PRS32_X API.
//-------------------------------------------------
extern void  PRS32_X_Start(void);
extern void  PRS32_X_Stop(void);
extern void  PRS32_X_WriteSeed(DWORD dwSeed);
extern void  PRS32_X_WritePolynomial(DWORD dwPolynomial);
extern void  PRS32_X_ReadPRS(DWORD * pdwPRSNumber);
//-------------------------------------------------
// Constants for PRS32_X API's.
//-------------------------------------------------

//-------------------------------------------------
// Register Addresses for PRS32_X
//-------------------------------------------------
#pragma ioport  PRS32_X_CONTROL_REG_LSB:    0x033          //Control register LSB
BYTE            PRS32_X_CONTROL_REG_LSB;
#pragma ioport  PRS32_X_CONTROL_REG_ISB1:   0x037          //Control register ISB1
BYTE            PRS32_X_CONTROL_REG_ISB1;
#pragma ioport  PRS32_X_CONTROL_REG_ISB2:   0x03b          //Control register ISB2
BYTE            PRS32_X_CONTROL_REG_ISB2;
#pragma ioport  PRS32_X_CONTROL_REG_MSB:    0x03f          //Control register MSB
BYTE            PRS32_X_CONTROL_REG_MSB;
#pragma ioport  PRS32_X_SHIFT_REG_LSB:  0x030              //Shift register LSB
BYTE            PRS32_X_SHIFT_REG_LSB;
#pragma ioport  PRS32_X_SHIFT_REG_ISB1: 0x034              //Shift register ISB1
BYTE            PRS32_X_SHIFT_REG_ISB1;
#pragma ioport  PRS32_X_SHIFT_REG_ISB2: 0x038              //Shift register ISB2
BYTE            PRS32_X_SHIFT_REG_ISB2;
#pragma ioport  PRS32_X_SHIFT_REG_MSB:  0x03c              //Shift register MSB
BYTE            PRS32_X_SHIFT_REG_MSB;
#pragma ioport  PRS32_X_POLY_REG_LSB:   0x031              //Polynomial register LSB
BYTE            PRS32_X_POLY_REG_LSB;
#pragma ioport  PRS32_X_POLY_REG_ISB1:  0x035              //Polynomial register ISB1
BYTE            PRS32_X_POLY_REG_ISB1;
#pragma ioport  PRS32_X_POLY_REG_ISB2:  0x039              //Polynomial register ISB2
BYTE            PRS32_X_POLY_REG_ISB2;
#pragma ioport  PRS32_X_POLY_REG_MSB:   0x03d              //Polynomial register MSB
BYTE            PRS32_X_POLY_REG_MSB;
#pragma ioport  PRS32_X_SEED_REG_LSB:   0x032              //Seed register LSB
BYTE            PRS32_X_SEED_REG_LSB;
#pragma ioport  PRS32_X_SEED_REG_ISB1:  0x036              //Seed register ISB1
BYTE            PRS32_X_SEED_REG_ISB1;
#pragma ioport  PRS32_X_SEED_REG_ISB2:  0x03a              //Seed register ISB2
BYTE            PRS32_X_SEED_REG_ISB2;
#pragma ioport  PRS32_X_SEED_REG_MSB:   0x03e              //Seed register MSB
BYTE            PRS32_X_SEED_REG_MSB;
#pragma ioport  PRS32_X_FUNC_REG_LSB:   0x130              //Function register LSB
BYTE            PRS32_X_FUNC_REG_LSB;
#pragma ioport  PRS32_X_FUNC_REG_ISB1:  0x134              //Function register ISB1
BYTE            PRS32_X_FUNC_REG_ISB1;
#pragma ioport  PRS32_X_FUNC_REG_ISB2:  0x138              //Function register ISB2
BYTE            PRS32_X_FUNC_REG_ISB2;
#pragma ioport  PRS32_X_FUNC_REG_MSB:   0x13c              //Function register MSB
BYTE            PRS32_X_FUNC_REG_MSB;
#pragma ioport  PRS32_X_INPUT_REG_LSB:  0x131              //Input register LSB
BYTE            PRS32_X_INPUT_REG_LSB;
#pragma ioport  PRS32_X_INPUT_REG_ISB1: 0x135              //Input register ISB1
BYTE            PRS32_X_INPUT_REG_ISB1;
#pragma ioport  PRS32_X_INPUT_REG_ISB2: 0x139              //Input register ISB2
BYTE            PRS32_X_INPUT_REG_ISB2;
#pragma ioport  PRS32_X_INPUT_REG_MSB:  0x13d              //Input register MSB
BYTE            PRS32_X_INPUT_REG_MSB;
#pragma ioport  PRS32_X_OUTPUT_REG_LSB: 0x132              //Output register LSB
BYTE            PRS32_X_OUTPUT_REG_LSB;
#pragma ioport  PRS32_X_OUTPUT_REG_ISB1:    0x136          //Output register ISB1
BYTE            PRS32_X_OUTPUT_REG_ISB1;
#pragma ioport  PRS32_X_OUTPUT_REG_ISB2:    0x13a          //Output register ISB2
BYTE            PRS32_X_OUTPUT_REG_ISB2;
#pragma ioport  PRS32_X_OUTPUT_REG_MSB: 0x13e              //Output register MSB
BYTE            PRS32_X_OUTPUT_REG_MSB;

#endif
// end of file PRS32_X.h
