/******************************************************************************
*  Generated by PSoC Designer 5.4.2946
******************************************************************************/
#include <m8c.h>
// LCD_1D4 address and mask defines
#pragma	ioport	LCD_1D4_Data_ADDR:	0x0
BYTE			LCD_1D4_Data_ADDR;
#pragma	ioport	LCD_1D4_DriveMode_0_ADDR:	0x100
BYTE			LCD_1D4_DriveMode_0_ADDR;
#pragma	ioport	LCD_1D4_DriveMode_1_ADDR:	0x101
BYTE			LCD_1D4_DriveMode_1_ADDR;
#pragma	ioport	LCD_1D4_DriveMode_2_ADDR:	0x3
BYTE			LCD_1D4_DriveMode_2_ADDR;
#pragma	ioport	LCD_1D4_GlobalSelect_ADDR:	0x2
BYTE			LCD_1D4_GlobalSelect_ADDR;
#pragma	ioport	LCD_1D4_IntCtrl_0_ADDR:	0x102
BYTE			LCD_1D4_IntCtrl_0_ADDR;
#pragma	ioport	LCD_1D4_IntCtrl_1_ADDR:	0x103
BYTE			LCD_1D4_IntCtrl_1_ADDR;
#pragma	ioport	LCD_1D4_IntEn_ADDR:	0x1
BYTE			LCD_1D4_IntEn_ADDR;
#define LCD_1D4_MASK 0x1
// LCD_1D4 Shadow defines
//   LCD_1D4_DataShadow define
extern BYTE Port_0_Data_SHADE;
#define LCD_1D4_DataShadow (*(unsigned char*)&Port_0_Data_SHADE)
//   LCD_1D4_DriveMode_0Shadow define
extern BYTE Port_0_DriveMode_0_SHADE;
#define LCD_1D4_DriveMode_0Shadow (*(unsigned char*)&Port_0_DriveMode_0_SHADE)
//   LCD_1D4_DriveMode_1Shadow define
extern BYTE Port_0_DriveMode_1_SHADE;
#define LCD_1D4_DriveMode_1Shadow (*(unsigned char*)&Port_0_DriveMode_1_SHADE)
// LCD_1D5 address and mask defines
#pragma	ioport	LCD_1D5_Data_ADDR:	0x0
BYTE			LCD_1D5_Data_ADDR;
#pragma	ioport	LCD_1D5_DriveMode_0_ADDR:	0x100
BYTE			LCD_1D5_DriveMode_0_ADDR;
#pragma	ioport	LCD_1D5_DriveMode_1_ADDR:	0x101
BYTE			LCD_1D5_DriveMode_1_ADDR;
#pragma	ioport	LCD_1D5_DriveMode_2_ADDR:	0x3
BYTE			LCD_1D5_DriveMode_2_ADDR;
#pragma	ioport	LCD_1D5_GlobalSelect_ADDR:	0x2
BYTE			LCD_1D5_GlobalSelect_ADDR;
#pragma	ioport	LCD_1D5_IntCtrl_0_ADDR:	0x102
BYTE			LCD_1D5_IntCtrl_0_ADDR;
#pragma	ioport	LCD_1D5_IntCtrl_1_ADDR:	0x103
BYTE			LCD_1D5_IntCtrl_1_ADDR;
#pragma	ioport	LCD_1D5_IntEn_ADDR:	0x1
BYTE			LCD_1D5_IntEn_ADDR;
#define LCD_1D5_MASK 0x2
// LCD_1D5 Shadow defines
//   LCD_1D5_DataShadow define
extern BYTE Port_0_Data_SHADE;
#define LCD_1D5_DataShadow (*(unsigned char*)&Port_0_Data_SHADE)
//   LCD_1D5_DriveMode_0Shadow define
extern BYTE Port_0_DriveMode_0_SHADE;
#define LCD_1D5_DriveMode_0Shadow (*(unsigned char*)&Port_0_DriveMode_0_SHADE)
//   LCD_1D5_DriveMode_1Shadow define
extern BYTE Port_0_DriveMode_1_SHADE;
#define LCD_1D5_DriveMode_1Shadow (*(unsigned char*)&Port_0_DriveMode_1_SHADE)
// LCD_1D6 address and mask defines
#pragma	ioport	LCD_1D6_Data_ADDR:	0x0
BYTE			LCD_1D6_Data_ADDR;
#pragma	ioport	LCD_1D6_DriveMode_0_ADDR:	0x100
BYTE			LCD_1D6_DriveMode_0_ADDR;
#pragma	ioport	LCD_1D6_DriveMode_1_ADDR:	0x101
BYTE			LCD_1D6_DriveMode_1_ADDR;
#pragma	ioport	LCD_1D6_DriveMode_2_ADDR:	0x3
BYTE			LCD_1D6_DriveMode_2_ADDR;
#pragma	ioport	LCD_1D6_GlobalSelect_ADDR:	0x2
BYTE			LCD_1D6_GlobalSelect_ADDR;
#pragma	ioport	LCD_1D6_IntCtrl_0_ADDR:	0x102
BYTE			LCD_1D6_IntCtrl_0_ADDR;
#pragma	ioport	LCD_1D6_IntCtrl_1_ADDR:	0x103
BYTE			LCD_1D6_IntCtrl_1_ADDR;
#pragma	ioport	LCD_1D6_IntEn_ADDR:	0x1
BYTE			LCD_1D6_IntEn_ADDR;
#define LCD_1D6_MASK 0x4
// LCD_1D6 Shadow defines
//   LCD_1D6_DataShadow define
extern BYTE Port_0_Data_SHADE;
#define LCD_1D6_DataShadow (*(unsigned char*)&Port_0_Data_SHADE)
//   LCD_1D6_DriveMode_0Shadow define
extern BYTE Port_0_DriveMode_0_SHADE;
#define LCD_1D6_DriveMode_0Shadow (*(unsigned char*)&Port_0_DriveMode_0_SHADE)
//   LCD_1D6_DriveMode_1Shadow define
extern BYTE Port_0_DriveMode_1_SHADE;
#define LCD_1D6_DriveMode_1Shadow (*(unsigned char*)&Port_0_DriveMode_1_SHADE)
// LCD_1D7 address and mask defines
#pragma	ioport	LCD_1D7_Data_ADDR:	0x0
BYTE			LCD_1D7_Data_ADDR;
#pragma	ioport	LCD_1D7_DriveMode_0_ADDR:	0x100
BYTE			LCD_1D7_DriveMode_0_ADDR;
#pragma	ioport	LCD_1D7_DriveMode_1_ADDR:	0x101
BYTE			LCD_1D7_DriveMode_1_ADDR;
#pragma	ioport	LCD_1D7_DriveMode_2_ADDR:	0x3
BYTE			LCD_1D7_DriveMode_2_ADDR;
#pragma	ioport	LCD_1D7_GlobalSelect_ADDR:	0x2
BYTE			LCD_1D7_GlobalSelect_ADDR;
#pragma	ioport	LCD_1D7_IntCtrl_0_ADDR:	0x102
BYTE			LCD_1D7_IntCtrl_0_ADDR;
#pragma	ioport	LCD_1D7_IntCtrl_1_ADDR:	0x103
BYTE			LCD_1D7_IntCtrl_1_ADDR;
#pragma	ioport	LCD_1D7_IntEn_ADDR:	0x1
BYTE			LCD_1D7_IntEn_ADDR;
#define LCD_1D7_MASK 0x8
// LCD_1D7 Shadow defines
//   LCD_1D7_DataShadow define
extern BYTE Port_0_Data_SHADE;
#define LCD_1D7_DataShadow (*(unsigned char*)&Port_0_Data_SHADE)
//   LCD_1D7_DriveMode_0Shadow define
extern BYTE Port_0_DriveMode_0_SHADE;
#define LCD_1D7_DriveMode_0Shadow (*(unsigned char*)&Port_0_DriveMode_0_SHADE)
//   LCD_1D7_DriveMode_1Shadow define
extern BYTE Port_0_DriveMode_1_SHADE;
#define LCD_1D7_DriveMode_1Shadow (*(unsigned char*)&Port_0_DriveMode_1_SHADE)
// LCD_1E address and mask defines
#pragma	ioport	LCD_1E_Data_ADDR:	0x0
BYTE			LCD_1E_Data_ADDR;
#pragma	ioport	LCD_1E_DriveMode_0_ADDR:	0x100
BYTE			LCD_1E_DriveMode_0_ADDR;
#pragma	ioport	LCD_1E_DriveMode_1_ADDR:	0x101
BYTE			LCD_1E_DriveMode_1_ADDR;
#pragma	ioport	LCD_1E_DriveMode_2_ADDR:	0x3
BYTE			LCD_1E_DriveMode_2_ADDR;
#pragma	ioport	LCD_1E_GlobalSelect_ADDR:	0x2
BYTE			LCD_1E_GlobalSelect_ADDR;
#pragma	ioport	LCD_1E_IntCtrl_0_ADDR:	0x102
BYTE			LCD_1E_IntCtrl_0_ADDR;
#pragma	ioport	LCD_1E_IntCtrl_1_ADDR:	0x103
BYTE			LCD_1E_IntCtrl_1_ADDR;
#pragma	ioport	LCD_1E_IntEn_ADDR:	0x1
BYTE			LCD_1E_IntEn_ADDR;
#define LCD_1E_MASK 0x10
// LCD_1E Shadow defines
//   LCD_1E_DataShadow define
extern BYTE Port_0_Data_SHADE;
#define LCD_1E_DataShadow (*(unsigned char*)&Port_0_Data_SHADE)
//   LCD_1E_DriveMode_0Shadow define
extern BYTE Port_0_DriveMode_0_SHADE;
#define LCD_1E_DriveMode_0Shadow (*(unsigned char*)&Port_0_DriveMode_0_SHADE)
//   LCD_1E_DriveMode_1Shadow define
extern BYTE Port_0_DriveMode_1_SHADE;
#define LCD_1E_DriveMode_1Shadow (*(unsigned char*)&Port_0_DriveMode_1_SHADE)
// LCD_1RS address and mask defines
#pragma	ioport	LCD_1RS_Data_ADDR:	0x0
BYTE			LCD_1RS_Data_ADDR;
#pragma	ioport	LCD_1RS_DriveMode_0_ADDR:	0x100
BYTE			LCD_1RS_DriveMode_0_ADDR;
#pragma	ioport	LCD_1RS_DriveMode_1_ADDR:	0x101
BYTE			LCD_1RS_DriveMode_1_ADDR;
#pragma	ioport	LCD_1RS_DriveMode_2_ADDR:	0x3
BYTE			LCD_1RS_DriveMode_2_ADDR;
#pragma	ioport	LCD_1RS_GlobalSelect_ADDR:	0x2
BYTE			LCD_1RS_GlobalSelect_ADDR;
#pragma	ioport	LCD_1RS_IntCtrl_0_ADDR:	0x102
BYTE			LCD_1RS_IntCtrl_0_ADDR;
#pragma	ioport	LCD_1RS_IntCtrl_1_ADDR:	0x103
BYTE			LCD_1RS_IntCtrl_1_ADDR;
#pragma	ioport	LCD_1RS_IntEn_ADDR:	0x1
BYTE			LCD_1RS_IntEn_ADDR;
#define LCD_1RS_MASK 0x20
// LCD_1RS Shadow defines
//   LCD_1RS_DataShadow define
extern BYTE Port_0_Data_SHADE;
#define LCD_1RS_DataShadow (*(unsigned char*)&Port_0_Data_SHADE)
//   LCD_1RS_DriveMode_0Shadow define
extern BYTE Port_0_DriveMode_0_SHADE;
#define LCD_1RS_DriveMode_0Shadow (*(unsigned char*)&Port_0_DriveMode_0_SHADE)
//   LCD_1RS_DriveMode_1Shadow define
extern BYTE Port_0_DriveMode_1_SHADE;
#define LCD_1RS_DriveMode_1Shadow (*(unsigned char*)&Port_0_DriveMode_1_SHADE)
// LCD_1RW address and mask defines
#pragma	ioport	LCD_1RW_Data_ADDR:	0x0
BYTE			LCD_1RW_Data_ADDR;
#pragma	ioport	LCD_1RW_DriveMode_0_ADDR:	0x100
BYTE			LCD_1RW_DriveMode_0_ADDR;
#pragma	ioport	LCD_1RW_DriveMode_1_ADDR:	0x101
BYTE			LCD_1RW_DriveMode_1_ADDR;
#pragma	ioport	LCD_1RW_DriveMode_2_ADDR:	0x3
BYTE			LCD_1RW_DriveMode_2_ADDR;
#pragma	ioport	LCD_1RW_GlobalSelect_ADDR:	0x2
BYTE			LCD_1RW_GlobalSelect_ADDR;
#pragma	ioport	LCD_1RW_IntCtrl_0_ADDR:	0x102
BYTE			LCD_1RW_IntCtrl_0_ADDR;
#pragma	ioport	LCD_1RW_IntCtrl_1_ADDR:	0x103
BYTE			LCD_1RW_IntCtrl_1_ADDR;
#pragma	ioport	LCD_1RW_IntEn_ADDR:	0x1
BYTE			LCD_1RW_IntEn_ADDR;
#define LCD_1RW_MASK 0x40
// LCD_1RW Shadow defines
//   LCD_1RW_DataShadow define
extern BYTE Port_0_Data_SHADE;
#define LCD_1RW_DataShadow (*(unsigned char*)&Port_0_Data_SHADE)
//   LCD_1RW_DriveMode_0Shadow define
extern BYTE Port_0_DriveMode_0_SHADE;
#define LCD_1RW_DriveMode_0Shadow (*(unsigned char*)&Port_0_DriveMode_0_SHADE)
//   LCD_1RW_DriveMode_1Shadow define
extern BYTE Port_0_DriveMode_1_SHADE;
#define LCD_1RW_DriveMode_1Shadow (*(unsigned char*)&Port_0_DriveMode_1_SHADE)
// ZBL address and mask defines
#pragma	ioport	ZBL_Data_ADDR:	0x0
BYTE			ZBL_Data_ADDR;
#pragma	ioport	ZBL_DriveMode_0_ADDR:	0x100
BYTE			ZBL_DriveMode_0_ADDR;
#pragma	ioport	ZBL_DriveMode_1_ADDR:	0x101
BYTE			ZBL_DriveMode_1_ADDR;
#pragma	ioport	ZBL_DriveMode_2_ADDR:	0x3
BYTE			ZBL_DriveMode_2_ADDR;
#pragma	ioport	ZBL_GlobalSelect_ADDR:	0x2
BYTE			ZBL_GlobalSelect_ADDR;
#pragma	ioport	ZBL_IntCtrl_0_ADDR:	0x102
BYTE			ZBL_IntCtrl_0_ADDR;
#pragma	ioport	ZBL_IntCtrl_1_ADDR:	0x103
BYTE			ZBL_IntCtrl_1_ADDR;
#pragma	ioport	ZBL_IntEn_ADDR:	0x1
BYTE			ZBL_IntEn_ADDR;
#define ZBL_MASK 0x80
// ZBL Shadow defines
//   ZBL_DataShadow define
extern BYTE Port_0_Data_SHADE;
#define ZBL_DataShadow (*(unsigned char*)&Port_0_Data_SHADE)
//   ZBL_DriveMode_0Shadow define
extern BYTE Port_0_DriveMode_0_SHADE;
#define ZBL_DriveMode_0Shadow (*(unsigned char*)&Port_0_DriveMode_0_SHADE)
//   ZBL_DriveMode_1Shadow define
extern BYTE Port_0_DriveMode_1_SHADE;
#define ZBL_DriveMode_1Shadow (*(unsigned char*)&Port_0_DriveMode_1_SHADE)
// XAL address and mask defines
#pragma	ioport	XAL_Data_ADDR:	0x4
BYTE			XAL_Data_ADDR;
#pragma	ioport	XAL_DriveMode_0_ADDR:	0x104
BYTE			XAL_DriveMode_0_ADDR;
#pragma	ioport	XAL_DriveMode_1_ADDR:	0x105
BYTE			XAL_DriveMode_1_ADDR;
#pragma	ioport	XAL_DriveMode_2_ADDR:	0x7
BYTE			XAL_DriveMode_2_ADDR;
#pragma	ioport	XAL_GlobalSelect_ADDR:	0x6
BYTE			XAL_GlobalSelect_ADDR;
#pragma	ioport	XAL_IntCtrl_0_ADDR:	0x106
BYTE			XAL_IntCtrl_0_ADDR;
#pragma	ioport	XAL_IntCtrl_1_ADDR:	0x107
BYTE			XAL_IntCtrl_1_ADDR;
#pragma	ioport	XAL_IntEn_ADDR:	0x5
BYTE			XAL_IntEn_ADDR;
#define XAL_MASK 0x4
// XAL Shadow defines
//   XAL_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define XAL_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// XAH address and mask defines
#pragma	ioport	XAH_Data_ADDR:	0x4
BYTE			XAH_Data_ADDR;
#pragma	ioport	XAH_DriveMode_0_ADDR:	0x104
BYTE			XAH_DriveMode_0_ADDR;
#pragma	ioport	XAH_DriveMode_1_ADDR:	0x105
BYTE			XAH_DriveMode_1_ADDR;
#pragma	ioport	XAH_DriveMode_2_ADDR:	0x7
BYTE			XAH_DriveMode_2_ADDR;
#pragma	ioport	XAH_GlobalSelect_ADDR:	0x6
BYTE			XAH_GlobalSelect_ADDR;
#pragma	ioport	XAH_IntCtrl_0_ADDR:	0x106
BYTE			XAH_IntCtrl_0_ADDR;
#pragma	ioport	XAH_IntCtrl_1_ADDR:	0x107
BYTE			XAH_IntCtrl_1_ADDR;
#pragma	ioport	XAH_IntEn_ADDR:	0x5
BYTE			XAH_IntEn_ADDR;
#define XAH_MASK 0x8
// XAH Shadow defines
//   XAH_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define XAH_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// XBH address and mask defines
#pragma	ioport	XBH_Data_ADDR:	0x4
BYTE			XBH_Data_ADDR;
#pragma	ioport	XBH_DriveMode_0_ADDR:	0x104
BYTE			XBH_DriveMode_0_ADDR;
#pragma	ioport	XBH_DriveMode_1_ADDR:	0x105
BYTE			XBH_DriveMode_1_ADDR;
#pragma	ioport	XBH_DriveMode_2_ADDR:	0x7
BYTE			XBH_DriveMode_2_ADDR;
#pragma	ioport	XBH_GlobalSelect_ADDR:	0x6
BYTE			XBH_GlobalSelect_ADDR;
#pragma	ioport	XBH_IntCtrl_0_ADDR:	0x106
BYTE			XBH_IntCtrl_0_ADDR;
#pragma	ioport	XBH_IntCtrl_1_ADDR:	0x107
BYTE			XBH_IntCtrl_1_ADDR;
#pragma	ioport	XBH_IntEn_ADDR:	0x5
BYTE			XBH_IntEn_ADDR;
#define XBH_MASK 0x10
// XBH Shadow defines
//   XBH_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define XBH_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// EzI2Cs_1SDA address and mask defines
#pragma	ioport	EzI2Cs_1SDA_Data_ADDR:	0x4
BYTE			EzI2Cs_1SDA_Data_ADDR;
#pragma	ioport	EzI2Cs_1SDA_DriveMode_0_ADDR:	0x104
BYTE			EzI2Cs_1SDA_DriveMode_0_ADDR;
#pragma	ioport	EzI2Cs_1SDA_DriveMode_1_ADDR:	0x105
BYTE			EzI2Cs_1SDA_DriveMode_1_ADDR;
#pragma	ioport	EzI2Cs_1SDA_DriveMode_2_ADDR:	0x7
BYTE			EzI2Cs_1SDA_DriveMode_2_ADDR;
#pragma	ioport	EzI2Cs_1SDA_GlobalSelect_ADDR:	0x6
BYTE			EzI2Cs_1SDA_GlobalSelect_ADDR;
#pragma	ioport	EzI2Cs_1SDA_IntCtrl_0_ADDR:	0x106
BYTE			EzI2Cs_1SDA_IntCtrl_0_ADDR;
#pragma	ioport	EzI2Cs_1SDA_IntCtrl_1_ADDR:	0x107
BYTE			EzI2Cs_1SDA_IntCtrl_1_ADDR;
#pragma	ioport	EzI2Cs_1SDA_IntEn_ADDR:	0x5
BYTE			EzI2Cs_1SDA_IntEn_ADDR;
#define EzI2Cs_1SDA_MASK 0x20
// EzI2Cs_1SDA Shadow defines
//   EzI2Cs_1SDA_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define EzI2Cs_1SDA_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// XBL address and mask defines
#pragma	ioport	XBL_Data_ADDR:	0x4
BYTE			XBL_Data_ADDR;
#pragma	ioport	XBL_DriveMode_0_ADDR:	0x104
BYTE			XBL_DriveMode_0_ADDR;
#pragma	ioport	XBL_DriveMode_1_ADDR:	0x105
BYTE			XBL_DriveMode_1_ADDR;
#pragma	ioport	XBL_DriveMode_2_ADDR:	0x7
BYTE			XBL_DriveMode_2_ADDR;
#pragma	ioport	XBL_GlobalSelect_ADDR:	0x6
BYTE			XBL_GlobalSelect_ADDR;
#pragma	ioport	XBL_IntCtrl_0_ADDR:	0x106
BYTE			XBL_IntCtrl_0_ADDR;
#pragma	ioport	XBL_IntCtrl_1_ADDR:	0x107
BYTE			XBL_IntCtrl_1_ADDR;
#pragma	ioport	XBL_IntEn_ADDR:	0x5
BYTE			XBL_IntEn_ADDR;
#define XBL_MASK 0x40
// XBL Shadow defines
//   XBL_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define XBL_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// EzI2Cs_1SCL address and mask defines
#pragma	ioport	EzI2Cs_1SCL_Data_ADDR:	0x4
BYTE			EzI2Cs_1SCL_Data_ADDR;
#pragma	ioport	EzI2Cs_1SCL_DriveMode_0_ADDR:	0x104
BYTE			EzI2Cs_1SCL_DriveMode_0_ADDR;
#pragma	ioport	EzI2Cs_1SCL_DriveMode_1_ADDR:	0x105
BYTE			EzI2Cs_1SCL_DriveMode_1_ADDR;
#pragma	ioport	EzI2Cs_1SCL_DriveMode_2_ADDR:	0x7
BYTE			EzI2Cs_1SCL_DriveMode_2_ADDR;
#pragma	ioport	EzI2Cs_1SCL_GlobalSelect_ADDR:	0x6
BYTE			EzI2Cs_1SCL_GlobalSelect_ADDR;
#pragma	ioport	EzI2Cs_1SCL_IntCtrl_0_ADDR:	0x106
BYTE			EzI2Cs_1SCL_IntCtrl_0_ADDR;
#pragma	ioport	EzI2Cs_1SCL_IntCtrl_1_ADDR:	0x107
BYTE			EzI2Cs_1SCL_IntCtrl_1_ADDR;
#pragma	ioport	EzI2Cs_1SCL_IntEn_ADDR:	0x5
BYTE			EzI2Cs_1SCL_IntEn_ADDR;
#define EzI2Cs_1SCL_MASK 0x80
// EzI2Cs_1SCL Shadow defines
//   EzI2Cs_1SCL_DataShadow define
extern BYTE Port_1_Data_SHADE;
#define EzI2Cs_1SCL_DataShadow (*(unsigned char*)&Port_1_Data_SHADE)
// YAH address and mask defines
#pragma	ioport	YAH_Data_ADDR:	0x8
BYTE			YAH_Data_ADDR;
#pragma	ioport	YAH_DriveMode_0_ADDR:	0x108
BYTE			YAH_DriveMode_0_ADDR;
#pragma	ioport	YAH_DriveMode_1_ADDR:	0x109
BYTE			YAH_DriveMode_1_ADDR;
#pragma	ioport	YAH_DriveMode_2_ADDR:	0xb
BYTE			YAH_DriveMode_2_ADDR;
#pragma	ioport	YAH_GlobalSelect_ADDR:	0xa
BYTE			YAH_GlobalSelect_ADDR;
#pragma	ioport	YAH_IntCtrl_0_ADDR:	0x10a
BYTE			YAH_IntCtrl_0_ADDR;
#pragma	ioport	YAH_IntCtrl_1_ADDR:	0x10b
BYTE			YAH_IntCtrl_1_ADDR;
#pragma	ioport	YAH_IntEn_ADDR:	0x9
BYTE			YAH_IntEn_ADDR;
#define YAH_MASK 0x1
// YAH Shadow defines
//   YAH_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define YAH_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
// YAL address and mask defines
#pragma	ioport	YAL_Data_ADDR:	0x8
BYTE			YAL_Data_ADDR;
#pragma	ioport	YAL_DriveMode_0_ADDR:	0x108
BYTE			YAL_DriveMode_0_ADDR;
#pragma	ioport	YAL_DriveMode_1_ADDR:	0x109
BYTE			YAL_DriveMode_1_ADDR;
#pragma	ioport	YAL_DriveMode_2_ADDR:	0xb
BYTE			YAL_DriveMode_2_ADDR;
#pragma	ioport	YAL_GlobalSelect_ADDR:	0xa
BYTE			YAL_GlobalSelect_ADDR;
#pragma	ioport	YAL_IntCtrl_0_ADDR:	0x10a
BYTE			YAL_IntCtrl_0_ADDR;
#pragma	ioport	YAL_IntCtrl_1_ADDR:	0x10b
BYTE			YAL_IntCtrl_1_ADDR;
#pragma	ioport	YAL_IntEn_ADDR:	0x9
BYTE			YAL_IntEn_ADDR;
#define YAL_MASK 0x2
// YAL Shadow defines
//   YAL_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define YAL_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
// ZAH address and mask defines
#pragma	ioport	ZAH_Data_ADDR:	0x8
BYTE			ZAH_Data_ADDR;
#pragma	ioport	ZAH_DriveMode_0_ADDR:	0x108
BYTE			ZAH_DriveMode_0_ADDR;
#pragma	ioport	ZAH_DriveMode_1_ADDR:	0x109
BYTE			ZAH_DriveMode_1_ADDR;
#pragma	ioport	ZAH_DriveMode_2_ADDR:	0xb
BYTE			ZAH_DriveMode_2_ADDR;
#pragma	ioport	ZAH_GlobalSelect_ADDR:	0xa
BYTE			ZAH_GlobalSelect_ADDR;
#pragma	ioport	ZAH_IntCtrl_0_ADDR:	0x10a
BYTE			ZAH_IntCtrl_0_ADDR;
#pragma	ioport	ZAH_IntCtrl_1_ADDR:	0x10b
BYTE			ZAH_IntCtrl_1_ADDR;
#pragma	ioport	ZAH_IntEn_ADDR:	0x9
BYTE			ZAH_IntEn_ADDR;
#define ZAH_MASK 0x4
// ZAH Shadow defines
//   ZAH_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define ZAH_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
// YBH address and mask defines
#pragma	ioport	YBH_Data_ADDR:	0x8
BYTE			YBH_Data_ADDR;
#pragma	ioport	YBH_DriveMode_0_ADDR:	0x108
BYTE			YBH_DriveMode_0_ADDR;
#pragma	ioport	YBH_DriveMode_1_ADDR:	0x109
BYTE			YBH_DriveMode_1_ADDR;
#pragma	ioport	YBH_DriveMode_2_ADDR:	0xb
BYTE			YBH_DriveMode_2_ADDR;
#pragma	ioport	YBH_GlobalSelect_ADDR:	0xa
BYTE			YBH_GlobalSelect_ADDR;
#pragma	ioport	YBH_IntCtrl_0_ADDR:	0x10a
BYTE			YBH_IntCtrl_0_ADDR;
#pragma	ioport	YBH_IntCtrl_1_ADDR:	0x10b
BYTE			YBH_IntCtrl_1_ADDR;
#pragma	ioport	YBH_IntEn_ADDR:	0x9
BYTE			YBH_IntEn_ADDR;
#define YBH_MASK 0x8
// YBH Shadow defines
//   YBH_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define YBH_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
// AGND address and mask defines
#pragma	ioport	AGND_Data_ADDR:	0x8
BYTE			AGND_Data_ADDR;
#pragma	ioport	AGND_DriveMode_0_ADDR:	0x108
BYTE			AGND_DriveMode_0_ADDR;
#pragma	ioport	AGND_DriveMode_1_ADDR:	0x109
BYTE			AGND_DriveMode_1_ADDR;
#pragma	ioport	AGND_DriveMode_2_ADDR:	0xb
BYTE			AGND_DriveMode_2_ADDR;
#pragma	ioport	AGND_GlobalSelect_ADDR:	0xa
BYTE			AGND_GlobalSelect_ADDR;
#pragma	ioport	AGND_IntCtrl_0_ADDR:	0x10a
BYTE			AGND_IntCtrl_0_ADDR;
#pragma	ioport	AGND_IntCtrl_1_ADDR:	0x10b
BYTE			AGND_IntCtrl_1_ADDR;
#pragma	ioport	AGND_IntEn_ADDR:	0x9
BYTE			AGND_IntEn_ADDR;
#define AGND_MASK 0x10
// AGND Shadow defines
//   AGND_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define AGND_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
// YBL address and mask defines
#pragma	ioport	YBL_Data_ADDR:	0x8
BYTE			YBL_Data_ADDR;
#pragma	ioport	YBL_DriveMode_0_ADDR:	0x108
BYTE			YBL_DriveMode_0_ADDR;
#pragma	ioport	YBL_DriveMode_1_ADDR:	0x109
BYTE			YBL_DriveMode_1_ADDR;
#pragma	ioport	YBL_DriveMode_2_ADDR:	0xb
BYTE			YBL_DriveMode_2_ADDR;
#pragma	ioport	YBL_GlobalSelect_ADDR:	0xa
BYTE			YBL_GlobalSelect_ADDR;
#pragma	ioport	YBL_IntCtrl_0_ADDR:	0x10a
BYTE			YBL_IntCtrl_0_ADDR;
#pragma	ioport	YBL_IntCtrl_1_ADDR:	0x10b
BYTE			YBL_IntCtrl_1_ADDR;
#pragma	ioport	YBL_IntEn_ADDR:	0x9
BYTE			YBL_IntEn_ADDR;
#define YBL_MASK 0x20
// YBL Shadow defines
//   YBL_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define YBL_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
// ZBH address and mask defines
#pragma	ioport	ZBH_Data_ADDR:	0x8
BYTE			ZBH_Data_ADDR;
#pragma	ioport	ZBH_DriveMode_0_ADDR:	0x108
BYTE			ZBH_DriveMode_0_ADDR;
#pragma	ioport	ZBH_DriveMode_1_ADDR:	0x109
BYTE			ZBH_DriveMode_1_ADDR;
#pragma	ioport	ZBH_DriveMode_2_ADDR:	0xb
BYTE			ZBH_DriveMode_2_ADDR;
#pragma	ioport	ZBH_GlobalSelect_ADDR:	0xa
BYTE			ZBH_GlobalSelect_ADDR;
#pragma	ioport	ZBH_IntCtrl_0_ADDR:	0x10a
BYTE			ZBH_IntCtrl_0_ADDR;
#pragma	ioport	ZBH_IntCtrl_1_ADDR:	0x10b
BYTE			ZBH_IntCtrl_1_ADDR;
#pragma	ioport	ZBH_IntEn_ADDR:	0x9
BYTE			ZBH_IntEn_ADDR;
#define ZBH_MASK 0x40
// ZBH Shadow defines
//   ZBH_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define ZBH_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
// ZAL address and mask defines
#pragma	ioport	ZAL_Data_ADDR:	0x8
BYTE			ZAL_Data_ADDR;
#pragma	ioport	ZAL_DriveMode_0_ADDR:	0x108
BYTE			ZAL_DriveMode_0_ADDR;
#pragma	ioport	ZAL_DriveMode_1_ADDR:	0x109
BYTE			ZAL_DriveMode_1_ADDR;
#pragma	ioport	ZAL_DriveMode_2_ADDR:	0xb
BYTE			ZAL_DriveMode_2_ADDR;
#pragma	ioport	ZAL_GlobalSelect_ADDR:	0xa
BYTE			ZAL_GlobalSelect_ADDR;
#pragma	ioport	ZAL_IntCtrl_0_ADDR:	0x10a
BYTE			ZAL_IntCtrl_0_ADDR;
#pragma	ioport	ZAL_IntCtrl_1_ADDR:	0x10b
BYTE			ZAL_IntCtrl_1_ADDR;
#pragma	ioport	ZAL_IntEn_ADDR:	0x9
BYTE			ZAL_IntEn_ADDR;
#define ZAL_MASK 0x80
// ZAL Shadow defines
//   ZAL_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define ZAL_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
