//*****************************************************************************
//*****************************************************************************
//  FILENAME: MBM_1.c
//  Version: 1.1, Updated on 2013/5/19 at 10:43:55
//  Generated by PSoC Designer 5.4.2946
//
//  DESCRIPTION: MBM_1 User Module C Language implementation file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2013. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************

#include "MBM_1.h"

// ---------------------------------------------------------------------------
//
// MBM_1_InitializeMailbox() - initializes mailbox
//
// arguments: 
//      pointer mailbox to initialize
//
// ---------------------------------------------------------------------------
void MBM_1_InitializeMailbox(void)
{
    // initialize flags
    MBM_1_MyMailbox.MailboxConfig0 &= ~MBM_1_BUSY ;             // clear busy flag
    MBM_1_MyMailbox.MailboxConfig0 &= ~MBM_1_DIRTY ;            // clear dirty flag
    // set mailbox size as identifier
    MBM_1_MyMailbox.MailboxConfig0 = sizeof(MBM_1_MyMailbox) ;           
}

// ---------------------------------------------------------------------------
//
// MBM_1_SetBusyFlag() - sets BUSY flag for mailbox.
//
// arguments: 
//      pointer mailbox where the BUSY flag needs to be set
//
// ---------------------------------------------------------------------------
void MBM_1_SetBusyFlag(void)
{
    MBM_1_MyMailbox.MailboxConfig0 |= MBM_1_BUSY ;        /* Set busy flag. */
}

// ---------------------------------------------------------------------------
//
// MBM_1_ClearBusyFlag() - clears BUSY flag in desired mailbox.
//
// arguments: 
//      pointer mailbox where the BUSY flag needs to be cleared
//
// ---------------------------------------------------------------------------
void MBM_1_ClearBusyFlag(void)
{
   MBM_1_MyMailbox.MailboxConfig0 &= ~MBM_1_BUSY ;        /* Set busy flag. */
}

// ---------------------------------------------------------------------------
//
// MBM_1_CheckDirtyFlag() - checks for DIRTY flag in desired mailbox.
//
// arguments: 
//      pointer mailbox where the check for DIRTY flag needs to be done
//
// ---------------------------------------------------------------------------
BYTE MBM_1_CheckDirtyFlag(void)
{
    if(MBM_1_MyMailbox.MailboxConfig0 & MBM_1_DIRTY)
		return TRUE;
	else
		return FALSE;
}

// ---------------------------------------------------------------------------
// MBM_1 global mailbox variable in RAM and pointer to this mailbox
// ---------------------------------------------------------------------------
MBM_1_Mailbox MBM_1_MyMailbox;
MBM_1_Mailbox* MBM_1_pMyMailbox;
