//*****************************************************************************
//*****************************************************************************
//  FILENAME: PRS32_Y.h
//   Version: 3.4, Updated on 2013/5/19 at 10:44:2
//  Generated by PSoC Designer 5.4.2946
//
//  DESCRIPTION: PRS32 User Module C Language interface file.
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2013. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef PRS32_Y_INCLUDE
#define PRS32_Y_INCLUDE

#include <m8c.h>

#pragma fastcall16  PRS32_Y_Start
#pragma fastcall16  PRS32_Y_Stop
#pragma fastcall16  PRS32_Y_WriteSeed
#pragma fastcall16  PRS32_Y_WritePolynomial
#pragma fastcall16  PRS32_Y_ReadPRS

//-------------------------------------------------
// Prototypes of the PRS32_Y API.
//-------------------------------------------------
extern void  PRS32_Y_Start(void);
extern void  PRS32_Y_Stop(void);
extern void  PRS32_Y_WriteSeed(DWORD dwSeed);
extern void  PRS32_Y_WritePolynomial(DWORD dwPolynomial);
extern void  PRS32_Y_ReadPRS(DWORD * pdwPRSNumber);
//-------------------------------------------------
// Constants for PRS32_Y API's.
//-------------------------------------------------

//-------------------------------------------------
// Register Addresses for PRS32_Y
//-------------------------------------------------
#pragma ioport  PRS32_Y_CONTROL_REG_LSB:    0x043          //Control register LSB
BYTE            PRS32_Y_CONTROL_REG_LSB;
#pragma ioport  PRS32_Y_CONTROL_REG_ISB1:   0x047          //Control register ISB1
BYTE            PRS32_Y_CONTROL_REG_ISB1;
#pragma ioport  PRS32_Y_CONTROL_REG_ISB2:   0x04b          //Control register ISB2
BYTE            PRS32_Y_CONTROL_REG_ISB2;
#pragma ioport  PRS32_Y_CONTROL_REG_MSB:    0x04f          //Control register MSB
BYTE            PRS32_Y_CONTROL_REG_MSB;
#pragma ioport  PRS32_Y_SHIFT_REG_LSB:  0x040              //Shift register LSB
BYTE            PRS32_Y_SHIFT_REG_LSB;
#pragma ioport  PRS32_Y_SHIFT_REG_ISB1: 0x044              //Shift register ISB1
BYTE            PRS32_Y_SHIFT_REG_ISB1;
#pragma ioport  PRS32_Y_SHIFT_REG_ISB2: 0x048              //Shift register ISB2
BYTE            PRS32_Y_SHIFT_REG_ISB2;
#pragma ioport  PRS32_Y_SHIFT_REG_MSB:  0x04c              //Shift register MSB
BYTE            PRS32_Y_SHIFT_REG_MSB;
#pragma ioport  PRS32_Y_POLY_REG_LSB:   0x041              //Polynomial register LSB
BYTE            PRS32_Y_POLY_REG_LSB;
#pragma ioport  PRS32_Y_POLY_REG_ISB1:  0x045              //Polynomial register ISB1
BYTE            PRS32_Y_POLY_REG_ISB1;
#pragma ioport  PRS32_Y_POLY_REG_ISB2:  0x049              //Polynomial register ISB2
BYTE            PRS32_Y_POLY_REG_ISB2;
#pragma ioport  PRS32_Y_POLY_REG_MSB:   0x04d              //Polynomial register MSB
BYTE            PRS32_Y_POLY_REG_MSB;
#pragma ioport  PRS32_Y_SEED_REG_LSB:   0x042              //Seed register LSB
BYTE            PRS32_Y_SEED_REG_LSB;
#pragma ioport  PRS32_Y_SEED_REG_ISB1:  0x046              //Seed register ISB1
BYTE            PRS32_Y_SEED_REG_ISB1;
#pragma ioport  PRS32_Y_SEED_REG_ISB2:  0x04a              //Seed register ISB2
BYTE            PRS32_Y_SEED_REG_ISB2;
#pragma ioport  PRS32_Y_SEED_REG_MSB:   0x04e              //Seed register MSB
BYTE            PRS32_Y_SEED_REG_MSB;
#pragma ioport  PRS32_Y_FUNC_REG_LSB:   0x140              //Function register LSB
BYTE            PRS32_Y_FUNC_REG_LSB;
#pragma ioport  PRS32_Y_FUNC_REG_ISB1:  0x144              //Function register ISB1
BYTE            PRS32_Y_FUNC_REG_ISB1;
#pragma ioport  PRS32_Y_FUNC_REG_ISB2:  0x148              //Function register ISB2
BYTE            PRS32_Y_FUNC_REG_ISB2;
#pragma ioport  PRS32_Y_FUNC_REG_MSB:   0x14c              //Function register MSB
BYTE            PRS32_Y_FUNC_REG_MSB;
#pragma ioport  PRS32_Y_INPUT_REG_LSB:  0x141              //Input register LSB
BYTE            PRS32_Y_INPUT_REG_LSB;
#pragma ioport  PRS32_Y_INPUT_REG_ISB1: 0x145              //Input register ISB1
BYTE            PRS32_Y_INPUT_REG_ISB1;
#pragma ioport  PRS32_Y_INPUT_REG_ISB2: 0x149              //Input register ISB2
BYTE            PRS32_Y_INPUT_REG_ISB2;
#pragma ioport  PRS32_Y_INPUT_REG_MSB:  0x14d              //Input register MSB
BYTE            PRS32_Y_INPUT_REG_MSB;
#pragma ioport  PRS32_Y_OUTPUT_REG_LSB: 0x142              //Output register LSB
BYTE            PRS32_Y_OUTPUT_REG_LSB;
#pragma ioport  PRS32_Y_OUTPUT_REG_ISB1:    0x146          //Output register ISB1
BYTE            PRS32_Y_OUTPUT_REG_ISB1;
#pragma ioport  PRS32_Y_OUTPUT_REG_ISB2:    0x14a          //Output register ISB2
BYTE            PRS32_Y_OUTPUT_REG_ISB2;
#pragma ioport  PRS32_Y_OUTPUT_REG_MSB: 0x14e              //Output register MSB
BYTE            PRS32_Y_OUTPUT_REG_MSB;

#endif
// end of file PRS32_Y.h
