//*****************************************************************************
//*****************************************************************************
//  FILENAME: PRS24_2.h
//   Version: 3.4, Updated on 2013/5/19 at 10:44:1
//  Generated by PSoC Designer 5.4.2946
//
//  DESCRIPTION: PRS24 User Module C Language interface file.
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2013. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef PRS24_2_INCLUDE
#define PRS24_2_INCLUDE

#include <m8c.h>

#pragma fastcall16  PRS24_2_Start
#pragma fastcall16  PRS24_2_Stop
#pragma fastcall16  PRS24_2_WriteSeed
#pragma fastcall16  PRS24_2_WritePolynomial
#pragma fastcall16  PRS24_2_ReadPRS

//-------------------------------------------------
// Prototypes of the PRS24_2 API.
//-------------------------------------------------
extern void  PRS24_2_Start(void);
extern void  PRS24_2_Stop(void);
extern void  PRS24_2_WriteSeed(DWORD dwSeed);
extern void  PRS24_2_WritePolynomial(DWORD dwPolynomial);
extern void  PRS24_2_ReadPRS(DWORD * pdwPRSNumber);

//-------------------------------------------------
// Register Addresses for PRS24_2
//-------------------------------------------------
#pragma ioport  PRS24_2_CONTROL_REG_LSB:    0x033          //Control register LSB
BYTE            PRS24_2_CONTROL_REG_LSB;
#pragma ioport  PRS24_2_CONTROL_REG_ISB:    0x037          //Control register ISB
BYTE            PRS24_2_CONTROL_REG_ISB;
#pragma ioport  PRS24_2_CONTROL_REG_MSB:    0x03b          //Control register MSB
BYTE            PRS24_2_CONTROL_REG_MSB;
#pragma ioport  PRS24_2_SHIFT_REG_LSB:  0x030              //Shift register LSB
BYTE            PRS24_2_SHIFT_REG_LSB;
#pragma ioport  PRS24_2_SHIFT_REG_ISB:  0x034              //Shift register ISB
BYTE            PRS24_2_SHIFT_REG_ISB;
#pragma ioport  PRS24_2_SHIFT_REG_MSB:  0x038              //Shift register MSB
BYTE            PRS24_2_SHIFT_REG_MSB;
#pragma ioport  PRS24_2_POLY_REG_LSB:   0x031              //Polynomial register LSB
BYTE            PRS24_2_POLY_REG_LSB;
#pragma ioport  PRS24_2_POLY_REG_ISB:   0x035              //Polynomial register ISB
BYTE            PRS24_2_POLY_REG_ISB;
#pragma ioport  PRS24_2_POLY_REG_MSB:   0x039              //Polynomial register MSB
BYTE            PRS24_2_POLY_REG_MSB;
#pragma ioport  PRS24_2_SEED_REG_LSB:   0x032              //Seed register LSB
BYTE            PRS24_2_SEED_REG_LSB;
#pragma ioport  PRS24_2_SEED_REG_ISB:   0x036              //Seed register ISB
BYTE            PRS24_2_SEED_REG_ISB;
#pragma ioport  PRS24_2_SEED_REG_MSB:   0x03a              //Seed register MSB
BYTE            PRS24_2_SEED_REG_MSB;
#pragma ioport  PRS24_2_FUNC_REG_LSB:   0x130              //Function register LSB
BYTE            PRS24_2_FUNC_REG_LSB;
#pragma ioport  PRS24_2_FUNC_REG_ISB:   0x134              //Function register ISB
BYTE            PRS24_2_FUNC_REG_ISB;
#pragma ioport  PRS24_2_FUNC_REG_MSB:   0x138              //Function register MSB
BYTE            PRS24_2_FUNC_REG_MSB;
#pragma ioport  PRS24_2_INPUT_REG_LSB:  0x131              //Input register LSB
BYTE            PRS24_2_INPUT_REG_LSB;
#pragma ioport  PRS24_2_INPUT_REG_ISB:  0x135              //Input register ISB
BYTE            PRS24_2_INPUT_REG_ISB;
#pragma ioport  PRS24_2_INPUT_REG_MSB:  0x139              //Input register MSB
BYTE            PRS24_2_INPUT_REG_MSB;
#pragma ioport  PRS24_2_OUTPUT_REG_LSB: 0x132              //Output register LSB
BYTE            PRS24_2_OUTPUT_REG_LSB;
#pragma ioport  PRS24_2_OUTPUT_REG_ISB: 0x136              //Output register ISB
BYTE            PRS24_2_OUTPUT_REG_ISB;
#pragma ioport  PRS24_2_OUTPUT_REG_MSB: 0x13a              //Output register MSB
BYTE            PRS24_2_OUTPUT_REG_MSB;

#endif
// end of file PRS24_2.h
