//*****************************************************************************
//*****************************************************************************
//  FILENAME: PRS24_3.h
//   Version: 3.4, Updated on 2013/5/19 at 10:44:1
//  Generated by PSoC Designer 5.4.2946
//
//  DESCRIPTION: PRS24 User Module C Language interface file.
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2013. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef PRS24_3_INCLUDE
#define PRS24_3_INCLUDE

#include <m8c.h>

#pragma fastcall16  PRS24_3_Start
#pragma fastcall16  PRS24_3_Stop
#pragma fastcall16  PRS24_3_WriteSeed
#pragma fastcall16  PRS24_3_WritePolynomial
#pragma fastcall16  PRS24_3_ReadPRS

//-------------------------------------------------
// Prototypes of the PRS24_3 API.
//-------------------------------------------------
extern void  PRS24_3_Start(void);
extern void  PRS24_3_Stop(void);
extern void  PRS24_3_WriteSeed(DWORD dwSeed);
extern void  PRS24_3_WritePolynomial(DWORD dwPolynomial);
extern void  PRS24_3_ReadPRS(DWORD * pdwPRSNumber);

//-------------------------------------------------
// Register Addresses for PRS24_3
//-------------------------------------------------
#pragma ioport  PRS24_3_CONTROL_REG_LSB:    0x03f          //Control register LSB
BYTE            PRS24_3_CONTROL_REG_LSB;
#pragma ioport  PRS24_3_CONTROL_REG_ISB:    0x043          //Control register ISB
BYTE            PRS24_3_CONTROL_REG_ISB;
#pragma ioport  PRS24_3_CONTROL_REG_MSB:    0x047          //Control register MSB
BYTE            PRS24_3_CONTROL_REG_MSB;
#pragma ioport  PRS24_3_SHIFT_REG_LSB:  0x03c              //Shift register LSB
BYTE            PRS24_3_SHIFT_REG_LSB;
#pragma ioport  PRS24_3_SHIFT_REG_ISB:  0x040              //Shift register ISB
BYTE            PRS24_3_SHIFT_REG_ISB;
#pragma ioport  PRS24_3_SHIFT_REG_MSB:  0x044              //Shift register MSB
BYTE            PRS24_3_SHIFT_REG_MSB;
#pragma ioport  PRS24_3_POLY_REG_LSB:   0x03d              //Polynomial register LSB
BYTE            PRS24_3_POLY_REG_LSB;
#pragma ioport  PRS24_3_POLY_REG_ISB:   0x041              //Polynomial register ISB
BYTE            PRS24_3_POLY_REG_ISB;
#pragma ioport  PRS24_3_POLY_REG_MSB:   0x045              //Polynomial register MSB
BYTE            PRS24_3_POLY_REG_MSB;
#pragma ioport  PRS24_3_SEED_REG_LSB:   0x03e              //Seed register LSB
BYTE            PRS24_3_SEED_REG_LSB;
#pragma ioport  PRS24_3_SEED_REG_ISB:   0x042              //Seed register ISB
BYTE            PRS24_3_SEED_REG_ISB;
#pragma ioport  PRS24_3_SEED_REG_MSB:   0x046              //Seed register MSB
BYTE            PRS24_3_SEED_REG_MSB;
#pragma ioport  PRS24_3_FUNC_REG_LSB:   0x13c              //Function register LSB
BYTE            PRS24_3_FUNC_REG_LSB;
#pragma ioport  PRS24_3_FUNC_REG_ISB:   0x140              //Function register ISB
BYTE            PRS24_3_FUNC_REG_ISB;
#pragma ioport  PRS24_3_FUNC_REG_MSB:   0x144              //Function register MSB
BYTE            PRS24_3_FUNC_REG_MSB;
#pragma ioport  PRS24_3_INPUT_REG_LSB:  0x13d              //Input register LSB
BYTE            PRS24_3_INPUT_REG_LSB;
#pragma ioport  PRS24_3_INPUT_REG_ISB:  0x141              //Input register ISB
BYTE            PRS24_3_INPUT_REG_ISB;
#pragma ioport  PRS24_3_INPUT_REG_MSB:  0x145              //Input register MSB
BYTE            PRS24_3_INPUT_REG_MSB;
#pragma ioport  PRS24_3_OUTPUT_REG_LSB: 0x13e              //Output register LSB
BYTE            PRS24_3_OUTPUT_REG_LSB;
#pragma ioport  PRS24_3_OUTPUT_REG_ISB: 0x142              //Output register ISB
BYTE            PRS24_3_OUTPUT_REG_ISB;
#pragma ioport  PRS24_3_OUTPUT_REG_MSB: 0x146              //Output register MSB
BYTE            PRS24_3_OUTPUT_REG_MSB;

#endif
// end of file PRS24_3.h
