//*****************************************************************************
//*****************************************************************************
//  FILENAME: PRS24_1.h
//   Version: 3.4, Updated on 2013/5/19 at 10:44:1
//  Generated by PSoC Designer 5.4.2946
//
//  DESCRIPTION: PRS24 User Module C Language interface file.
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2013. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef PRS24_1_INCLUDE
#define PRS24_1_INCLUDE

#include <m8c.h>

#pragma fastcall16  PRS24_1_Start
#pragma fastcall16  PRS24_1_Stop
#pragma fastcall16  PRS24_1_WriteSeed
#pragma fastcall16  PRS24_1_WritePolynomial
#pragma fastcall16  PRS24_1_ReadPRS

//-------------------------------------------------
// Prototypes of the PRS24_1 API.
//-------------------------------------------------
extern void  PRS24_1_Start(void);
extern void  PRS24_1_Stop(void);
extern void  PRS24_1_WriteSeed(DWORD dwSeed);
extern void  PRS24_1_WritePolynomial(DWORD dwPolynomial);
extern void  PRS24_1_ReadPRS(DWORD * pdwPRSNumber);

//-------------------------------------------------
// Register Addresses for PRS24_1
//-------------------------------------------------
#pragma ioport  PRS24_1_CONTROL_REG_LSB:    0x023          //Control register LSB
BYTE            PRS24_1_CONTROL_REG_LSB;
#pragma ioport  PRS24_1_CONTROL_REG_ISB:    0x027          //Control register ISB
BYTE            PRS24_1_CONTROL_REG_ISB;
#pragma ioport  PRS24_1_CONTROL_REG_MSB:    0x02b          //Control register MSB
BYTE            PRS24_1_CONTROL_REG_MSB;
#pragma ioport  PRS24_1_SHIFT_REG_LSB:  0x020              //Shift register LSB
BYTE            PRS24_1_SHIFT_REG_LSB;
#pragma ioport  PRS24_1_SHIFT_REG_ISB:  0x024              //Shift register ISB
BYTE            PRS24_1_SHIFT_REG_ISB;
#pragma ioport  PRS24_1_SHIFT_REG_MSB:  0x028              //Shift register MSB
BYTE            PRS24_1_SHIFT_REG_MSB;
#pragma ioport  PRS24_1_POLY_REG_LSB:   0x021              //Polynomial register LSB
BYTE            PRS24_1_POLY_REG_LSB;
#pragma ioport  PRS24_1_POLY_REG_ISB:   0x025              //Polynomial register ISB
BYTE            PRS24_1_POLY_REG_ISB;
#pragma ioport  PRS24_1_POLY_REG_MSB:   0x029              //Polynomial register MSB
BYTE            PRS24_1_POLY_REG_MSB;
#pragma ioport  PRS24_1_SEED_REG_LSB:   0x022              //Seed register LSB
BYTE            PRS24_1_SEED_REG_LSB;
#pragma ioport  PRS24_1_SEED_REG_ISB:   0x026              //Seed register ISB
BYTE            PRS24_1_SEED_REG_ISB;
#pragma ioport  PRS24_1_SEED_REG_MSB:   0x02a              //Seed register MSB
BYTE            PRS24_1_SEED_REG_MSB;
#pragma ioport  PRS24_1_FUNC_REG_LSB:   0x120              //Function register LSB
BYTE            PRS24_1_FUNC_REG_LSB;
#pragma ioport  PRS24_1_FUNC_REG_ISB:   0x124              //Function register ISB
BYTE            PRS24_1_FUNC_REG_ISB;
#pragma ioport  PRS24_1_FUNC_REG_MSB:   0x128              //Function register MSB
BYTE            PRS24_1_FUNC_REG_MSB;
#pragma ioport  PRS24_1_INPUT_REG_LSB:  0x121              //Input register LSB
BYTE            PRS24_1_INPUT_REG_LSB;
#pragma ioport  PRS24_1_INPUT_REG_ISB:  0x125              //Input register ISB
BYTE            PRS24_1_INPUT_REG_ISB;
#pragma ioport  PRS24_1_INPUT_REG_MSB:  0x129              //Input register MSB
BYTE            PRS24_1_INPUT_REG_MSB;
#pragma ioport  PRS24_1_OUTPUT_REG_LSB: 0x122              //Output register LSB
BYTE            PRS24_1_OUTPUT_REG_LSB;
#pragma ioport  PRS24_1_OUTPUT_REG_ISB: 0x126              //Output register ISB
BYTE            PRS24_1_OUTPUT_REG_ISB;
#pragma ioport  PRS24_1_OUTPUT_REG_MSB: 0x12a              //Output register MSB
BYTE            PRS24_1_OUTPUT_REG_MSB;

#endif
// end of file PRS24_1.h
