//*****************************************************************************
//*****************************************************************************
//  FILENAME: PRS8_2.h
//   Version: 3.4, Updated on 2013/5/19 at 10:44:3
//  Generated by PSoC Designer 5.4.2946
//
//  DESCRIPTION: PRS8 User Module C Language interface file.
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2013. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef PRS8_2_INCLUDE
#define PRS8_2_INCLUDE

#include <m8c.h>

#pragma fastcall16  PRS8_2_Start
#pragma fastcall16  PRS8_2_Stop
#pragma fastcall16  PRS8_2_WriteSeed
#pragma fastcall16  PRS8_2_WritePolynomial
#pragma fastcall16  PRS8_2_bReadPRS

//-------------------------------------------------
// Prototypes of the PRS8_2 API.
//-------------------------------------------------
extern void  PRS8_2_Start(void);
extern void  PRS8_2_Stop(void);
extern void  PRS8_2_WriteSeed(BYTE bSeed);
extern void  PRS8_2_WritePolynomial(BYTE bPolynomial);
extern BYTE  PRS8_2_bReadPRS(void);

//-------------------------------------------------
// Do not use! For backwards compatibility only.
#pragma fastcall16 bPRS8_2_ReadPRS
extern BYTE bPRS8_2_ReadPRS(void);
//-------------------------------------------------

//-------------------------------------------------
// Register Addresses for PRS8_2
//-------------------------------------------------
#pragma ioport  PRS8_2_CONTROL_REG: 0x027                  //Control register LSB
BYTE            PRS8_2_CONTROL_REG;
#pragma ioport  PRS8_2_SHIFT_REG:   0x024                  //Shift register LSB
BYTE            PRS8_2_SHIFT_REG;
#pragma ioport  PRS8_2_POLY_REG:    0x025                  //Polynomial register LSB
BYTE            PRS8_2_POLY_REG;
#pragma ioport  PRS8_2_SEED_REG:    0x026                  //Seed register LSB
BYTE            PRS8_2_SEED_REG;
#pragma ioport  PRS8_2_FUNC_REG:    0x124                  //Function register LSB
BYTE            PRS8_2_FUNC_REG;
#pragma ioport  PRS8_2_INPUT_REG:   0x125                  //Input register LSB
BYTE            PRS8_2_INPUT_REG;
#pragma ioport  PRS8_2_OUTPUT_REG:  0x126                  //Output register LSB
BYTE            PRS8_2_OUTPUT_REG;

#endif
// end of file PRS8_2.h
