//*****************************************************************************
//*****************************************************************************
//  FILENAME: PRS8_1.h
//   Version: 3.4, Updated on 2013/5/19 at 10:44:3
//  Generated by PSoC Designer 5.4.2946
//
//  DESCRIPTION: PRS8 User Module C Language interface file.
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2013. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef PRS8_1_INCLUDE
#define PRS8_1_INCLUDE

#include <m8c.h>

#pragma fastcall16  PRS8_1_Start
#pragma fastcall16  PRS8_1_Stop
#pragma fastcall16  PRS8_1_WriteSeed
#pragma fastcall16  PRS8_1_WritePolynomial
#pragma fastcall16  PRS8_1_bReadPRS

//-------------------------------------------------
// Prototypes of the PRS8_1 API.
//-------------------------------------------------
extern void  PRS8_1_Start(void);
extern void  PRS8_1_Stop(void);
extern void  PRS8_1_WriteSeed(BYTE bSeed);
extern void  PRS8_1_WritePolynomial(BYTE bPolynomial);
extern BYTE  PRS8_1_bReadPRS(void);

//-------------------------------------------------
// Do not use! For backwards compatibility only.
#pragma fastcall16 bPRS8_1_ReadPRS
extern BYTE bPRS8_1_ReadPRS(void);
//-------------------------------------------------

//-------------------------------------------------
// Register Addresses for PRS8_1
//-------------------------------------------------
#pragma ioport  PRS8_1_CONTROL_REG: 0x023                  //Control register LSB
BYTE            PRS8_1_CONTROL_REG;
#pragma ioport  PRS8_1_SHIFT_REG:   0x020                  //Shift register LSB
BYTE            PRS8_1_SHIFT_REG;
#pragma ioport  PRS8_1_POLY_REG:    0x021                  //Polynomial register LSB
BYTE            PRS8_1_POLY_REG;
#pragma ioport  PRS8_1_SEED_REG:    0x022                  //Seed register LSB
BYTE            PRS8_1_SEED_REG;
#pragma ioport  PRS8_1_FUNC_REG:    0x120                  //Function register LSB
BYTE            PRS8_1_FUNC_REG;
#pragma ioport  PRS8_1_INPUT_REG:   0x121                  //Input register LSB
BYTE            PRS8_1_INPUT_REG;
#pragma ioport  PRS8_1_OUTPUT_REG:  0x122                  //Output register LSB
BYTE            PRS8_1_OUTPUT_REG;

#endif
// end of file PRS8_1.h
