//*****************************************************************************
//*****************************************************************************
//  FILENAME: MBM_1.h
//   Version: 1.1, Updated on 2013/5/19 at 10:43:55
//  Generated by PSoC Designer 5.4.2946
//
//  DESCRIPTION: MBM_1 User Module C Language interface file  
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2013. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************

#ifndef MBM_1_include
#define MBM_1_include

#include <m8c.h>

//--------------------------------------------------
// constants for mailboxes
//--------------------------------------------------
#define MBM_1_SERVICE_VARS_ABOVE               0
#define MBM_1_SERVICE_VARS_BELOW               1
// mailbox service variables position
#define MBM_1_SERVICE_VARS_POSITION            MBM_1_SERVICE_VARS_ABOVE // Position of service variables in structure

// offset of service bytes
#define MBM_1_CONFIG_0                         0
#define MBM_1_CONFIG_1                         1

#define MBM_1_BUSY                             0x80   // Busy Flag - set by the slave to tell the host not to read data until cleared
#define MBM_1_DIRTY                            0x40   // Dirty Flag - set by the host to denote that data is in the process of being written and that the slave should not read data from the mailbox until it is cleared

// variables aliases (offset inside of structure)
// access to some structure member:
//(TYPE)* (MBM_1_pMyMailbox+Alias)
#define MAILBOXCONFIG0		 0x00
#define MAILBOXCONFIG1		 0x01
#define OUTB_RESERVED_0		 0x02
#define SERVO_DEG_1		 0x03
#define SERVO_DEG_2		 0x04
#define SERVO_DEG_3		 0x05
#define SERVO_DEG_4		 0x06
#define SERVO_DEG_5		 0x07
#define SERVO_DEG_6		 0x08
#define SERVO_DEG_7		 0x09
#define SERVO_DEG_8		 0x0A
#define AIR_1		 0x0B
#define INB_RESERVED_1		 0x0C


//--------------------------------------------------
// typedefs for mailboxes
//--------------------------------------------------

typedef struct
{
	BYTE reserved0; 			// reserved variable
	BYTE servo_deg_1; 			// 
	BYTE servo_deg_2; 			// 
	BYTE servo_deg_3; 			// 
	BYTE servo_deg_4; 			// 
	BYTE servo_deg_5; 			// 
	BYTE servo_deg_6; 			// 
	BYTE servo_deg_7; 			// 
	BYTE servo_deg_8; 			// 
	BYTE air_1; 			// 

} MBM_1_Outbox;

typedef struct
{
	BYTE reserved1; 			// reserved variable

} MBM_1_Inbox;

typedef struct
{
    #if (MBM_1_SERVICE_VARS_POSITION == MBM_1_SERVICE_VARS_ABOVE)

	BYTE MailboxConfig0; 			// Reserved for Mailbox UM usage
	BYTE MailboxConfig1; 			// Reserved for Mailbox UM usage

    #endif

    MBM_1_Outbox Outbox;
    MBM_1_Inbox Inbox;

    #if (MBM_1_SERVICE_VARS_POSITION == MBM_1_SERVICE_VARS_BELOW)

	BYTE MailboxConfig0; 			// Reserved for Mailbox UM usage
	BYTE MailboxConfig1; 			// Reserved for Mailbox UM usage

    #endif
} MBM_1_Mailbox;

//-------------------------------------------------
// C prototypes of the MBM_1 API.
//-------------------------------------------------
extern void MBM_1_InitializeMailbox(void);
extern void MBM_1_SetBusyFlag(void);
extern void MBM_1_ClearBusyFlag(void);
extern BYTE MBM_1_CheckDirtyFlag(void);

// ---------------------------------------------------------------------------
// MBM_1 global mailbox variable in RAM
// ---------------------------------------------------------------------------
extern MBM_1_Mailbox MBM_1_MyMailbox;
extern MBM_1_Mailbox* MBM_1_pMyMailbox;

#endif
