//*****************************************************************************
//*****************************************************************************
//  FILENAME: PWM16_6.h
//   Version: 2.5, Updated on 2013/5/19 at 10:44:6
//  Generated by PSoC Designer 5.4.2946
//
//  DESCRIPTION: PWM16 User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2013. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef PWM16_6_INCLUDE
#define PWM16_6_INCLUDE

#include <m8c.h>

#pragma fastcall16 PWM16_6_EnableInt
#pragma fastcall16 PWM16_6_DisableInt
#pragma fastcall16 PWM16_6_Start
#pragma fastcall16 PWM16_6_Stop
#pragma fastcall16 PWM16_6_wReadCounter              // Read  DR0
#pragma fastcall16 PWM16_6_WritePeriod               // Write DR1
#pragma fastcall16 PWM16_6_wReadPulseWidth           // Read  DR2
#pragma fastcall16 PWM16_6_WritePulseWidth           // Write DR2

// The following symbols are deprecated.
// They may be omitted in future releases
//
#pragma fastcall16 wPWM16_6_ReadCounter              // Read  DR0 (Deprecated)
#pragma fastcall16 wPWM16_6_ReadPulseWidth           // Read  DR2 (Deprecated)


//-------------------------------------------------
// Prototypes of the PWM16_6 API.
//-------------------------------------------------

extern void PWM16_6_EnableInt(void);                  // Proxy Class 1
extern void PWM16_6_DisableInt(void);                 // Proxy Class 1
extern void PWM16_6_Start(void);                      // Proxy Class 1
extern void PWM16_6_Stop(void);                       // Proxy Class 1
extern WORD PWM16_6_wReadCounter(void);               // Proxy Class 2
extern void PWM16_6_WritePeriod(WORD wPeriod);        // Proxy Class 1
extern WORD PWM16_6_wReadPulseWidth(void);            // Proxy Class 1
extern void PWM16_6_WritePulseWidth(WORD wPulseWidth);// Proxy Class 1

// The following functions are deprecated.
// They may be omitted in future releases
//
extern WORD wPWM16_6_ReadCounter(void);            // Deprecated
extern WORD wPWM16_6_ReadPulseWidth(void);         // Deprecated


//-------------------------------------------------
// Constants for PWM16_6 API's.
//-------------------------------------------------

#define PWM16_6_CONTROL_REG_START_BIT          ( 0x01 )
#define PWM16_6_INT_REG_ADDR                   ( 0x0df )
#define PWM16_6_INT_MASK                       ( 0x08 )


//--------------------------------------------------
// Constants for PWM16_6 user defined values
//--------------------------------------------------

#define PWM16_6_PERIOD                         ( 0x5dbf )
#define PWM16_6_PULSE_WIDTH                    ( 0x4af )


//-------------------------------------------------
// Register Addresses for PWM16_6
//-------------------------------------------------

#pragma ioport  PWM16_6_COUNTER_LSB_REG:    0x048          //DR0 Count register LSB
BYTE            PWM16_6_COUNTER_LSB_REG;
#pragma ioport  PWM16_6_COUNTER_MSB_REG:    0x04c          //DR0 Count register MSB
BYTE            PWM16_6_COUNTER_MSB_REG;
#pragma ioport  PWM16_6_PERIOD_LSB_REG: 0x049              //DR1 Period register LSB
BYTE            PWM16_6_PERIOD_LSB_REG;
#pragma ioport  PWM16_6_PERIOD_MSB_REG: 0x04d              //DR1 Period register MSB
BYTE            PWM16_6_PERIOD_MSB_REG;
#pragma ioport  PWM16_6_COMPARE_LSB_REG:    0x04a          //DR2 Compare register LSB
BYTE            PWM16_6_COMPARE_LSB_REG;
#pragma ioport  PWM16_6_COMPARE_MSB_REG:    0x04e          //DR2 Compare register MSB
BYTE            PWM16_6_COMPARE_MSB_REG;
#pragma ioport  PWM16_6_CONTROL_LSB_REG:    0x04b          //Control register LSB
BYTE            PWM16_6_CONTROL_LSB_REG;
#pragma ioport  PWM16_6_CONTROL_MSB_REG:    0x04f          //Control register MSB
BYTE            PWM16_6_CONTROL_MSB_REG;
#pragma ioport  PWM16_6_FUNC_LSB_REG:   0x148              //Function register LSB
BYTE            PWM16_6_FUNC_LSB_REG;
#pragma ioport  PWM16_6_FUNC_MSB_REG:   0x14c              //Function register MSB
BYTE            PWM16_6_FUNC_MSB_REG;
#pragma ioport  PWM16_6_INPUT_LSB_REG:  0x149              //Input register LSB
BYTE            PWM16_6_INPUT_LSB_REG;
#pragma ioport  PWM16_6_INPUT_MSB_REG:  0x14d              //Input register MSB
BYTE            PWM16_6_INPUT_MSB_REG;
#pragma ioport  PWM16_6_OUTPUT_LSB_REG: 0x14a              //Output register LSB
BYTE            PWM16_6_OUTPUT_LSB_REG;
#pragma ioport  PWM16_6_OUTPUT_MSB_REG: 0x14e              //Output register MSB
BYTE            PWM16_6_OUTPUT_MSB_REG;
#pragma ioport  PWM16_6_INT_REG:       0x0df               //Interrupt Mask Register
BYTE            PWM16_6_INT_REG;


//-------------------------------------------------
// PWM16_6 Macro 'Functions'
//-------------------------------------------------

#define PWM16_6_Start_M \
   ( PWM16_6_CONTROL_LSB_REG |=  PWM16_6_CONTROL_REG_START_BIT )

#define PWM16_6_Stop_M  \
   ( PWM16_6_CONTROL_LSB_REG &= ~PWM16_6_CONTROL_REG_START_BIT )

#define PWM16_6_EnableInt_M   \
   M8C_EnableIntMask(  PWM16_6_INT_REG, PWM16_6_INT_MASK )

#define PWM16_6_DisableInt_M  \
   M8C_DisableIntMask( PWM16_6_INT_REG, PWM16_6_INT_MASK )

#endif
// end of file PWM16_6.h
