//*****************************************************************************
//*****************************************************************************
//  FILENAME: PWM16_7.h
//   Version: 2.5, Updated on 2013/5/19 at 10:44:6
//  Generated by PSoC Designer 5.4.2946
//
//  DESCRIPTION: PWM16 User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2013. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef PWM16_7_INCLUDE
#define PWM16_7_INCLUDE

#include <m8c.h>

#pragma fastcall16 PWM16_7_EnableInt
#pragma fastcall16 PWM16_7_DisableInt
#pragma fastcall16 PWM16_7_Start
#pragma fastcall16 PWM16_7_Stop
#pragma fastcall16 PWM16_7_wReadCounter              // Read  DR0
#pragma fastcall16 PWM16_7_WritePeriod               // Write DR1
#pragma fastcall16 PWM16_7_wReadPulseWidth           // Read  DR2
#pragma fastcall16 PWM16_7_WritePulseWidth           // Write DR2

// The following symbols are deprecated.
// They may be omitted in future releases
//
#pragma fastcall16 wPWM16_7_ReadCounter              // Read  DR0 (Deprecated)
#pragma fastcall16 wPWM16_7_ReadPulseWidth           // Read  DR2 (Deprecated)


//-------------------------------------------------
// Prototypes of the PWM16_7 API.
//-------------------------------------------------

extern void PWM16_7_EnableInt(void);                  // Proxy Class 1
extern void PWM16_7_DisableInt(void);                 // Proxy Class 1
extern void PWM16_7_Start(void);                      // Proxy Class 1
extern void PWM16_7_Stop(void);                       // Proxy Class 1
extern WORD PWM16_7_wReadCounter(void);               // Proxy Class 2
extern void PWM16_7_WritePeriod(WORD wPeriod);        // Proxy Class 1
extern WORD PWM16_7_wReadPulseWidth(void);            // Proxy Class 1
extern void PWM16_7_WritePulseWidth(WORD wPulseWidth);// Proxy Class 1

// The following functions are deprecated.
// They may be omitted in future releases
//
extern WORD wPWM16_7_ReadCounter(void);            // Deprecated
extern WORD wPWM16_7_ReadPulseWidth(void);         // Deprecated


//-------------------------------------------------
// Constants for PWM16_7 API's.
//-------------------------------------------------

#define PWM16_7_CONTROL_REG_START_BIT          ( 0x01 )
#define PWM16_7_INT_REG_ADDR                   ( 0x0df )
#define PWM16_7_INT_MASK                       ( 0x20 )


//--------------------------------------------------
// Constants for PWM16_7 user defined values
//--------------------------------------------------

#define PWM16_7_PERIOD                         ( 0x5dbf )
#define PWM16_7_PULSE_WIDTH                    ( 0x4af )


//-------------------------------------------------
// Register Addresses for PWM16_7
//-------------------------------------------------

#pragma ioport  PWM16_7_COUNTER_LSB_REG:    0x050          //DR0 Count register LSB
BYTE            PWM16_7_COUNTER_LSB_REG;
#pragma ioport  PWM16_7_COUNTER_MSB_REG:    0x054          //DR0 Count register MSB
BYTE            PWM16_7_COUNTER_MSB_REG;
#pragma ioport  PWM16_7_PERIOD_LSB_REG: 0x051              //DR1 Period register LSB
BYTE            PWM16_7_PERIOD_LSB_REG;
#pragma ioport  PWM16_7_PERIOD_MSB_REG: 0x055              //DR1 Period register MSB
BYTE            PWM16_7_PERIOD_MSB_REG;
#pragma ioport  PWM16_7_COMPARE_LSB_REG:    0x052          //DR2 Compare register LSB
BYTE            PWM16_7_COMPARE_LSB_REG;
#pragma ioport  PWM16_7_COMPARE_MSB_REG:    0x056          //DR2 Compare register MSB
BYTE            PWM16_7_COMPARE_MSB_REG;
#pragma ioport  PWM16_7_CONTROL_LSB_REG:    0x053          //Control register LSB
BYTE            PWM16_7_CONTROL_LSB_REG;
#pragma ioport  PWM16_7_CONTROL_MSB_REG:    0x057          //Control register MSB
BYTE            PWM16_7_CONTROL_MSB_REG;
#pragma ioport  PWM16_7_FUNC_LSB_REG:   0x150              //Function register LSB
BYTE            PWM16_7_FUNC_LSB_REG;
#pragma ioport  PWM16_7_FUNC_MSB_REG:   0x154              //Function register MSB
BYTE            PWM16_7_FUNC_MSB_REG;
#pragma ioport  PWM16_7_INPUT_LSB_REG:  0x151              //Input register LSB
BYTE            PWM16_7_INPUT_LSB_REG;
#pragma ioport  PWM16_7_INPUT_MSB_REG:  0x155              //Input register MSB
BYTE            PWM16_7_INPUT_MSB_REG;
#pragma ioport  PWM16_7_OUTPUT_LSB_REG: 0x152              //Output register LSB
BYTE            PWM16_7_OUTPUT_LSB_REG;
#pragma ioport  PWM16_7_OUTPUT_MSB_REG: 0x156              //Output register MSB
BYTE            PWM16_7_OUTPUT_MSB_REG;
#pragma ioport  PWM16_7_INT_REG:       0x0df               //Interrupt Mask Register
BYTE            PWM16_7_INT_REG;


//-------------------------------------------------
// PWM16_7 Macro 'Functions'
//-------------------------------------------------

#define PWM16_7_Start_M \
   ( PWM16_7_CONTROL_LSB_REG |=  PWM16_7_CONTROL_REG_START_BIT )

#define PWM16_7_Stop_M  \
   ( PWM16_7_CONTROL_LSB_REG &= ~PWM16_7_CONTROL_REG_START_BIT )

#define PWM16_7_EnableInt_M   \
   M8C_EnableIntMask(  PWM16_7_INT_REG, PWM16_7_INT_MASK )

#define PWM16_7_DisableInt_M  \
   M8C_DisableIntMask( PWM16_7_INT_REG, PWM16_7_INT_MASK )

#endif
// end of file PWM16_7.h
