//*****************************************************************************
//*****************************************************************************
//  FILENAME: PWM16_3.h
//   Version: 2.5, Updated on 2013/5/19 at 10:44:6
//  Generated by PSoC Designer 5.4.2946
//
//  DESCRIPTION: PWM16 User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2013. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef PWM16_3_INCLUDE
#define PWM16_3_INCLUDE

#include <m8c.h>

#pragma fastcall16 PWM16_3_EnableInt
#pragma fastcall16 PWM16_3_DisableInt
#pragma fastcall16 PWM16_3_Start
#pragma fastcall16 PWM16_3_Stop
#pragma fastcall16 PWM16_3_wReadCounter              // Read  DR0
#pragma fastcall16 PWM16_3_WritePeriod               // Write DR1
#pragma fastcall16 PWM16_3_wReadPulseWidth           // Read  DR2
#pragma fastcall16 PWM16_3_WritePulseWidth           // Write DR2

// The following symbols are deprecated.
// They may be omitted in future releases
//
#pragma fastcall16 wPWM16_3_ReadCounter              // Read  DR0 (Deprecated)
#pragma fastcall16 wPWM16_3_ReadPulseWidth           // Read  DR2 (Deprecated)


//-------------------------------------------------
// Prototypes of the PWM16_3 API.
//-------------------------------------------------

extern void PWM16_3_EnableInt(void);                  // Proxy Class 1
extern void PWM16_3_DisableInt(void);                 // Proxy Class 1
extern void PWM16_3_Start(void);                      // Proxy Class 1
extern void PWM16_3_Stop(void);                       // Proxy Class 1
extern WORD PWM16_3_wReadCounter(void);               // Proxy Class 2
extern void PWM16_3_WritePeriod(WORD wPeriod);        // Proxy Class 1
extern WORD PWM16_3_wReadPulseWidth(void);            // Proxy Class 1
extern void PWM16_3_WritePulseWidth(WORD wPulseWidth);// Proxy Class 1

// The following functions are deprecated.
// They may be omitted in future releases
//
extern WORD wPWM16_3_ReadCounter(void);            // Deprecated
extern WORD wPWM16_3_ReadPulseWidth(void);         // Deprecated


//-------------------------------------------------
// Constants for PWM16_3 API's.
//-------------------------------------------------

#define PWM16_3_CONTROL_REG_START_BIT          ( 0x01 )
#define PWM16_3_INT_REG_ADDR                   ( 0x0e1 )
#define PWM16_3_INT_MASK                       ( 0x20 )


//--------------------------------------------------
// Constants for PWM16_3 user defined values
//--------------------------------------------------

#define PWM16_3_PERIOD                         ( 0x5dbf )
#define PWM16_3_PULSE_WIDTH                    ( 0x898 )


//-------------------------------------------------
// Register Addresses for PWM16_3
//-------------------------------------------------

#pragma ioport  PWM16_3_COUNTER_LSB_REG:    0x030          //DR0 Count register LSB
BYTE            PWM16_3_COUNTER_LSB_REG;
#pragma ioport  PWM16_3_COUNTER_MSB_REG:    0x034          //DR0 Count register MSB
BYTE            PWM16_3_COUNTER_MSB_REG;
#pragma ioport  PWM16_3_PERIOD_LSB_REG: 0x031              //DR1 Period register LSB
BYTE            PWM16_3_PERIOD_LSB_REG;
#pragma ioport  PWM16_3_PERIOD_MSB_REG: 0x035              //DR1 Period register MSB
BYTE            PWM16_3_PERIOD_MSB_REG;
#pragma ioport  PWM16_3_COMPARE_LSB_REG:    0x032          //DR2 Compare register LSB
BYTE            PWM16_3_COMPARE_LSB_REG;
#pragma ioport  PWM16_3_COMPARE_MSB_REG:    0x036          //DR2 Compare register MSB
BYTE            PWM16_3_COMPARE_MSB_REG;
#pragma ioport  PWM16_3_CONTROL_LSB_REG:    0x033          //Control register LSB
BYTE            PWM16_3_CONTROL_LSB_REG;
#pragma ioport  PWM16_3_CONTROL_MSB_REG:    0x037          //Control register MSB
BYTE            PWM16_3_CONTROL_MSB_REG;
#pragma ioport  PWM16_3_FUNC_LSB_REG:   0x130              //Function register LSB
BYTE            PWM16_3_FUNC_LSB_REG;
#pragma ioport  PWM16_3_FUNC_MSB_REG:   0x134              //Function register MSB
BYTE            PWM16_3_FUNC_MSB_REG;
#pragma ioport  PWM16_3_INPUT_LSB_REG:  0x131              //Input register LSB
BYTE            PWM16_3_INPUT_LSB_REG;
#pragma ioport  PWM16_3_INPUT_MSB_REG:  0x135              //Input register MSB
BYTE            PWM16_3_INPUT_MSB_REG;
#pragma ioport  PWM16_3_OUTPUT_LSB_REG: 0x132              //Output register LSB
BYTE            PWM16_3_OUTPUT_LSB_REG;
#pragma ioport  PWM16_3_OUTPUT_MSB_REG: 0x136              //Output register MSB
BYTE            PWM16_3_OUTPUT_MSB_REG;
#pragma ioport  PWM16_3_INT_REG:       0x0e1               //Interrupt Mask Register
BYTE            PWM16_3_INT_REG;


//-------------------------------------------------
// PWM16_3 Macro 'Functions'
//-------------------------------------------------

#define PWM16_3_Start_M \
   ( PWM16_3_CONTROL_LSB_REG |=  PWM16_3_CONTROL_REG_START_BIT )

#define PWM16_3_Stop_M  \
   ( PWM16_3_CONTROL_LSB_REG &= ~PWM16_3_CONTROL_REG_START_BIT )

#define PWM16_3_EnableInt_M   \
   M8C_EnableIntMask(  PWM16_3_INT_REG, PWM16_3_INT_MASK )

#define PWM16_3_DisableInt_M  \
   M8C_DisableIntMask( PWM16_3_INT_REG, PWM16_3_INT_MASK )

#endif
// end of file PWM16_3.h
